@extends('web.layout')
@section('title', $item->title.' — CGJobs')
@push('head')
<meta property="og:title" content="{{ $item->title }}"><meta property="og:description" content="{{ $item->summary }}"><meta property="og:type" content="article"><meta property="og:url" content="{{ url()->current() }}">@if($item->image_url)<meta property="og:image" content="{{ str_starts_with($item->image_url,'http') ? $item->image_url : asset(ltrim($item->image_url,'/')) }}">@endif
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>$type === 'jobs' ? 'JobPosting' : 'Article','headline'=>$item->title,'description'=>$item->summary,'image'=>$item->image_url ? (str_starts_with($item->image_url,'http') ? $item->image_url : asset(ltrim($item->image_url,'/'))) : null,'datePublished'=>$item->published_at ?: optional($item->created_at)->toIso8601String(),'dateModified'=>optional($item->updated_at)->toIso8601String(),'mainEntityOfPage'=>url()->current(),'url'=>url()->current(),'publisher'=>['@type'=>'Organization','name'=>'CGJobs']], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>
@endpush
@section('content')
<div class="article-wrap"><div class="container"><div class="article-layout"><article class="article">
@if($item->image_url)<img src="{{ str_starts_with($item->image_url,'http') ? $item->image_url : asset(ltrim($item->image_url,'/')) }}" alt="{{ $item->title }}" style="width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:20px;margin-bottom:22px">@endif
<div class="meta-row"><span class="pill">{{ $item->category ?: ($type === 'jobs' ? 'Government Job' : 'Current Affairs') }}</span>@if($item->is_new)<span class="pill pill-new">NEW</span>@endif @if($item->is_breaking)<span class="pill pill-breaking">BREAKING</span>@endif</div><h1>{{ $item->title }}</h1><div class="date">{{ $item->published_at ?: optional($item->created_at)->format('d M Y') }} · {{ $item->source ?: 'CGJobs' }}</div>
@if($item->summary)<p class="article-lead" style="margin-top:24px">{{ $item->summary }}</p>@endif
@if($type === 'jobs')<div class="facts">@foreach([['Vacancies',$item->vacancies],['Salary',$item->salary],['Eligibility',$item->eligibility],['Age Limit',$item->age_limit],['Application Start',$item->application_start],['Last Date',$item->last_date],['Exam Date',$item->exam_date],['Selection',$item->selection_process]] as $row) @if($row[1])<div class="fact"><label>{{ $row[0] }}</label><strong>{{ $row[1] }}</strong></div>@endif @endforeach</div>@endif
@if($item->detailed_content)<div class="content"><h2>Detailed Information</h2><div style="white-space:pre-line">{{ $item->detailed_content }}</div></div>@endif
<div class="article-actions"><a class="btn btn-primary" href="https://play.google.com/store">📱 See in App</a>@if($item->official_notification_url)<a class="btn btn-outline" target="_blank" rel="noopener" href="{{ $item->official_notification_url }}">Official Notification ↗</a>@endif @if($item->apply_url)<a class="btn btn-outline" target="_blank" rel="noopener" href="{{ $item->apply_url }}">Apply Now ↗</a>@endif</div></article>
<aside class="side">@if($related->count())<div class="side-card"><h3>Related {{ $type === 'jobs' ? 'Updates' : 'News' }}</h3>@foreach($related as $r)<a class="side-link" href="{{ route($type === 'current-affairs' ? 'current-affairs.show' : 'job.show',$r->custom_id ?: $r->id) }}">{{ $r->title }}</a>@endforeach</div>@endif<div class="side-card" style="margin-top:12px"><h3>CGJobs App</h3><p style="font-size:12px;color:#64748b;line-height:1.6;margin:0">इस exact update को Android app में पढ़ें और save करें।</p><a class="read" href="https://play.google.com/store">Open app →</a></div></aside></div></div></div>
@endsection
