@extends('web.layout')
@section('title', $item->title.' — CGJobs')
@push('head')<meta property="og:title" content="{{ $item->title }}"><meta property="og:description" content="{{ $item->summary }}"><script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$item->title,'description'=>$item->summary,'datePublished'=>$item->published_at ?: optional($item->created_at)->toIso8601String(),'mainEntityOfPage'=>url()->current()], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>@endpush
@section('content')
<div class="container mx-auto px-4 py-10"><div class="max-w-4xl mx-auto">
<div class="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span class="bg-slate-100 px-2.5 py-1 rounded-full font-bold">{{ $item->category ?: ($type === 'jobs' ? 'Government Job' : 'Current Affairs') }}</span>@if($item->is_new)<span class="bg-emerald-100 text-emerald-700 px-2.5 py-1 rounded-full font-bold">NEW</span>@endif @if($item->is_breaking)<span class="bg-rose-100 text-rose-700 px-2.5 py-1 rounded-full font-bold">BREAKING</span>@endif</div>
<h1 class="text-3xl md:text-5xl font-black tracking-tight leading-tight mt-5">{{ $item->title }}</h1><div class="text-sm text-slate-400 mt-4">{{ $item->published_at ?: optional($item->created_at)->format('d M Y') }} · {{ $item->source ?: 'CGJobs' }}</div>
<div class="mt-7 rounded-2xl border bg-white p-6 md:p-8 shadow-sm"><p class="text-lg leading-8 text-slate-700">{{ $item->summary }}</p>
@if($type === 'jobs')<div class="grid sm:grid-cols-2 gap-3 mt-7">@foreach([['Vacancies',$item->vacancies],['Salary',$item->salary],['Eligibility',$item->eligibility],['Age Limit',$item->age_limit],['Application Start',$item->application_start],['Last Date',$item->last_date],['Exam Date',$item->exam_date],['Selection',$item->selection_process]] as $row) @if($row[1])<div class="rounded-xl bg-slate-50 p-4"><div class="text-xs text-slate-400 font-bold">{{ $row[0] }}</div><div class="font-bold mt-1">{{ $row[1] }}</div></div>@endif @endforeach</div>@endif
@if($item->detailed_content)<div class="mt-8 pt-7 border-t"><h2 class="text-xl font-black mb-3">Detailed Information</h2><div class="prose max-w-none whitespace-pre-line leading-7 text-slate-700">{{ $item->detailed_content }}</div></div>@endif
<div class="mt-8 flex flex-wrap gap-3"><a href="https://play.google.com/store" class="inline-flex bg-slate-950 text-white px-5 py-3 rounded-xl font-bold">📱 See in App</a>@if($item->official_notification_url)<a target="_blank" rel="noopener" href="{{ $item->official_notification_url }}" class="inline-flex border px-5 py-3 rounded-xl font-bold">Official Notification ↗</a>@endif @if($item->apply_url)<a target="_blank" rel="noopener" href="{{ $item->apply_url }}" class="inline-flex border px-5 py-3 rounded-xl font-bold">Apply Now ↗</a>@endif</div>
</div>
@if($related->count())<section class="mt-10"><h2 class="text-xl font-black mb-4">You may also like</h2><div class="grid sm:grid-cols-2 gap-4">@foreach($related as $r)<a href="{{ route('job.show',$r->custom_id ?: $r->id) }}" class="bg-white border rounded-2xl p-4 hover:shadow-md"><div class="font-bold line-clamp-2">{{ $r->title }}</div><div class="text-xs text-slate-400 mt-2">{{ $r->category }}</div></a>@endforeach</div></section>@endif
</div></div>
@endsection