@extends('web.layout')
@section('title', $lang==='en' ? 'CGJobs — Government Jobs, Exams, Current Affairs & GK' : 'CGJobs — सरकारी नौकरी, परीक्षा, Current Affairs & GK')
@section('content')
@php
$categories = [
 ['name'=>'CGSSB','desc'=>$lang==='en'?'Chhattisgarh Staff Selection Board':'छत्तीसगढ़ कर्मचारी चयन मंडल','icon'=>'🏛️','tone'=>'blue'],
 ['name'=>'CGPSC','desc'=>$lang==='en'?'Chhattisgarh Public Service Commission':'छत्तीसगढ़ लोक सेवा आयोग','icon'=>'📜','tone'=>'violet'],
 ['name'=>'Central Govt','desc'=>$lang==='en'?'All India Government Jobs':'केंद्र सरकार की नौकरियां','icon'=>'🇮🇳','tone'=>'amber'],
 ['name'=>'Contractual','desc'=>$lang==='en'?'Contract / Temporary Jobs':'संविदा / अस्थायी नौकरियां','icon'=>'📄','tone'=>'green'],
];
$departments=['Education','Police','Health','Forest','Revenue','PWD','Women & Child Development','Agriculture','Panchayat','Other Departments'];
$trending=$latest->take(4);
$hot=$jobs->filter(fn($j)=>$j->is_breaking || $j->is_new)->take(5);
if($hot->isEmpty()) $hot=$jobs->take(5);
@endphp

<section class="hero hero-home"><div class="hero-glow"></div><div class="container hero-home-inner">
 <div class="hero-copy"><span class="hero-kicker">🇮🇳 {{ $lang==='en'?'Government Jobs • Exams • Preparation':'सरकारी नौकरी • परीक्षा • तैयारी' }}</span><h1>{{ $lang==='en'?'Your Government Job Starts Here':'आपकी सरकारी नौकरी की शुरुआत यहीं से' }}</h1><p>{{ $lang==='en'?'Latest government jobs, exam updates, current affairs and Static GK — all in one trusted place.':'नवीनतम सरकारी नौकरी, परीक्षा अपडेट, Current Affairs और Static GK — सब एक ही भरोसेमंद जगह पर।' }}</p>
 <form class="hero-search" action="{{ route('listing.jobs',['lang'=>$lang]) }}" method="get"><span>⌕</span><input name="q" placeholder="{{ $lang==='en'?'Search jobs, exams, departments, posts...':'नौकरी, परीक्षा, विभाग, पद खोजें...' }}"><button>{{ $lang==='en'?'Search':'खोजें' }}</button></form>
 <div class="popular"><b>{{ $lang==='en'?'Popular:':'लोकप्रिय:' }}</b><a href="{{ route('listing.jobs',['lang'=>$lang,'job_category'=>'CGSSB']) }}">CGSSB</a><a href="{{ route('listing.jobs',['lang'=>$lang,'job_category'=>'CGPSC']) }}">CGPSC</a><a href="{{ route('listing.jobs',['lang'=>$lang,'job_category'=>'Central Govt']) }}">SSC</a><a href="{{ route('listing.jobs',['lang'=>$lang,'job_category'=>'Central Govt']) }}">Railway</a><a href="{{ route('listing.jobs',['lang'=>$lang,'job_category'=>'Central Govt']) }}">Banking</a><a href="{{ route('listing.current-affairs',['lang'=>$lang]) }}">Current Affairs</a></div></div>
 <div class="hero-side"><div class="hero-side-top"><span>🔥</span><div><b>{{ $lang==='en'?'Important today':'आज के महत्वपूर्ण अपडेट' }}</b><small>{{ $lang==='en'?'Stay ahead of the latest notifications':'नवीनतम notifications से आगे रहें' }}</small></div></div>@forelse($latest->take(5) as $item)<a class="hero-news" href="{{ route('job.show',$item->custom_id ?: $item->id,['lang'=>$lang]) }}"><span>{{ $loop->iteration }}</span><div><small>{{ $item->job_category ?: ($item->category ?: 'CGJobs') }}</small><strong>{{ $item->title }}</strong></div><i>→</i></a>@empty<div class="empty">{{ $lang==='en'?'New updates will appear here soon.':'नई updates जल्द यहाँ दिखाई देंगी।' }}</div>@endforelse</div>
</div></section>

<section class="section category-section"><div class="container"><div class="section-head"><div><span class="section-kicker">{{ $lang==='en'?'Find your path':'अपनी category चुनें' }}</span><h2>{{ $lang==='en'?'Explore Government Jobs':'सरकारी नौकरियां खोजें' }}</h2><p>{{ $lang==='en'?'Four major job categories. One simple destination.':'चार प्रमुख job categories — एक आसान destination।' }}</p></div></div><div class="category-grid">@foreach($categories as $cat)<a class="category-card cat-{{ $cat['tone'] }}" href="{{ route('listing.jobs',['lang'=>$lang,'job_category'=>$cat['name']]) }}"><span class="category-icon">{{ $cat['icon'] }}</span><div><h3>{{ $cat['name'] }}</h3><p>{{ $cat['desc'] }}</p></div><span class="arrow">→</span></a>@endforeach</div>
<div class="department-strip"><b>Departments</b>@foreach($departments as $department)<a href="{{ route('listing.jobs',['lang'=>$lang,'department'=>$department]) }}">{{ $department }}</a>@endforeach</div></div></section>

<section class="section section-tint"><div class="container"><div class="section-head"><div><span class="section-kicker red">🔥 {{ $lang==='en'?'Most important right now':'अभी के सबसे महत्वपूर्ण अपडेट' }}</span><h2>{{ $lang==='en'?'Trending Job Notifications':'Trending Job Notifications' }}</h2><p>{{ $lang==='en'?'Important and widely viewed government recruitment updates.':'महत्वपूर्ण और सबसे ज्यादा देखी जा रही सरकारी भर्ती notifications।' }}</p></div><a class="section-link" href="{{ route('listing.jobs',['lang'=>$lang]) }}">{{ $lang==='en'?'View all →':'सभी देखें →' }}</a></div><div class="job-card-grid">@forelse($trending as $item)<article class="job-card"><div class="job-card-top"><div class="badges">@if($item->is_breaking)<span class="badge hot">HOT</span>@endif @if($item->is_new)<span class="badge new">NEW</span>@endif</div><span class="date">{{ $item->relative_time ?: ($lang==='en'?'Recently':'हाल में') }}</span></div><div class="job-logo">{{ strtoupper(substr($item->job_category ?: 'CG',0,2)) }}</div><h3>{{ $item->title }}</h3><p class="department">{{ $item->department ?: ($item->category ?: 'Government Recruitment') }}</p><div class="job-meta"><span>👥 {{ $item->vacancies ?: '—' }} {{ $lang==='en'?'Vacancies':'पद' }}</span><span>📅 {{ $item->last_date ?: '—' }}</span></div><div class="tags"><span>{{ $item->job_category ?: 'Government Job' }}</span>@if($item->post_type)<span>{{ $item->post_type }}</span>@endif</div><a class="job-button" href="{{ route('job.show',$item->custom_id ?: $item->id,['lang'=>$lang]) }}">{{ $lang==='en'?'View Notification →':'Notification देखें →' }}</a></article>@empty<div class="empty-card">{{ $lang==='en'?'Trending jobs will appear here.':'Trending jobs यहाँ दिखाई देंगी।' }}</div>@endforelse</div></div></section>

<section class="section"><div class="container"><div class="section-head"><div><span class="section-kicker">🆕 {{ $lang==='en'?'Freshly published':'अभी प्रकाशित' }}</span><h2>{{ $lang==='en'?'Latest Government Jobs':'Latest Government Jobs' }}</h2></div><a class="section-link" href="{{ route('listing.jobs',['lang'=>$lang]) }}">{{ $lang==='en'?'View all jobs →':'सभी Jobs →' }}</a></div><div class="latest-layout"><div class="latest-list">@forelse($jobs->take(7) as $item)<a class="latest-row" href="{{ route('job.show',$item->custom_id ?: $item->id,['lang'=>$lang]) }}"><span class="latest-icon">💼</span><span class="latest-main"><strong>{{ $item->title }}</strong><small>{{ $item->department ?: 'Government Department' }}</small></span><span class="latest-info"><b>{{ $item->vacancies ?: '—' }}</b><small>{{ $lang==='en'?'Vacancies':'पद' }}</small></span><span class="latest-deadline">{{ $item->last_date ?: '—' }}</span><span class="row-arrow">→</span></a>@empty<div class="empty-card">{{ $lang==='en'?'No published jobs yet.':'अभी कोई published job नहीं है।' }}</div>@endforelse</div><aside class="hot-panel"><div class="panel-title"><span>🔥</span><div><h3>{{ $lang==='en'?'Hot Jobs':'Hot Jobs' }}</h3><small>{{ $lang==='en'?'Worth checking today':'आज जरूर देखें' }}</small></div><a href="{{ route('listing.jobs',['lang'=>$lang]) }}">→</a></div>@foreach($hot as $item)<a class="hot-row" href="{{ route('job.show',$item->custom_id ?: $item->id,['lang'=>$lang]) }}"><span class="rank">{{ $loop->iteration }}</span><span><strong>{{ $item->title }}</strong><small>{{ $item->vacancies ?: '—' }} {{ $lang==='en'?'Vacancies':'पद' }}</small></span></a>@endforeach</aside></div></div></section>

<section class="section section-tint"><div class="container"><div class="section-head"><div><span class="section-kicker">📚 {{ $lang==='en'?'Job ↔ Exam':'Job ↔ Exam' }}</span><h2>{{ $lang==='en'?'Every Government Job Has an Exam Path':'हर सरकारी नौकरी का अपना Exam Path' }}</h2><p>{{ $lang==='en'?'Connect recruitment notifications with the exam, syllabus, admit card and result.':'Recruitment notification को exam, syllabus, admit card और result से जोड़ें।' }}</p></div></div><div class="exam-flow"><div><span>💼</span><b>{{ $lang==='en'?'Job Notification':'Job Notification' }}</b><small>{{ $lang==='en'?'Vacancy & eligibility':'Vacancy & eligibility' }}</small></div><i>→</i><div><span>📝</span><b>{{ $lang==='en'?'Examination':'Examination' }}</b><small>{{ $lang==='en'?'Pattern & dates':'Pattern & dates' }}</small></div><i>→</i><div><span>📖</span><b>{{ $lang==='en'?'Syllabus & Papers':'Syllabus & Papers' }}</b><small>{{ $lang==='en'?'Prepare smarter':'Prepare smarter' }}</small></div><i>→</i><div><span>🏆</span><b>{{ $lang==='en'?'Admit Card & Result':'Admit Card & Result' }}</b><small>{{ $lang==='en'?'Track every stage':'Track every stage' }}</small></div></div></div></section>

<section class="section"><div class="container"><div class="section-head"><div><span class="section-kicker">📰 {{ $lang==='en'?'Daily preparation':'दैनिक तैयारी' }}</span><h2>{{ $lang==='en'?'Today’s Current Affairs':'आज के Current Affairs' }}</h2></div><a class="section-link" href="{{ route('listing.current-affairs',['lang'=>$lang]) }}">{{ $lang==='en'?'View all →':'सभी देखें →' }}</a></div><div class="content-grid">@forelse($currentAffairs->take(6) as $item)<a class="news-card" href="{{ route('current-affairs.show',$item->custom_id ?: $item->id,['lang'=>$lang]) }}"><span class="news-icon">📰</span><div><span class="news-cat">{{ $item->category ?: 'Current Affairs' }}</span><h3>{{ $item->title }}</h3><small>{{ $item->relative_time ?: ($lang==='en'?'Recently':'हाल में') }}</small></div></a>@empty<div class="empty-card">{{ $lang==='en'?'Current Affairs will appear here.':'Current Affairs यहाँ दिखाई देंगे।' }}</div>@endforelse</div></div></section>

<section class="section gk-section"><div class="container"><div class="section-head"><div><span class="section-kicker">🧠 {{ $lang==='en'?'Exam preparation':'परीक्षा तैयारी' }}</span><h2>Static GK</h2><p>{{ $lang==='en'?'Build strong fundamentals for government exams.':'सरकारी परीक्षाओं के लिए मजबूत आधार तैयार करें।' }}</p></div><a class="section-link" href="{{ route('listing.gk',['lang'=>$lang]) }}">{{ $lang==='en'?'Explore GK →':'GK देखें →' }}</a></div><div class="gk-grid">@forelse($gk->take(6) as $item)<a class="gk-card" href="{{ route('gk.show',$item->custom_id ?: $item->id,['lang'=>$lang]) }}"><span class="gk-icon">📘</span><div><span>{{ $item->category ?: 'General Knowledge' }}</span><h3>{{ $item->title }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags($item->answer ?: $item->detailed_notes ?: ''),100) }}</p></div><b>→</b></a>@empty<div class="empty-card">{{ $lang==='en'?'GK content will appear here.':'GK content जल्द जोड़ा जाएगा।' }}</div>@endforelse</div></div></section>

<section class="section"><div class="container utility-grid"><div class="utility-card"><span>📋</span><div><h3>{{ $lang==='en'?'Admit Cards':'Admit Cards' }}</h3><p>{{ $lang==='en'?'Latest admit card updates':'नवीनतम admit card updates' }}</p></div><a href="#">→</a></div><div class="utility-card"><span>🏆</span><div><h3>{{ $lang==='en'?'Results':'Results' }}</h3><p>{{ $lang==='en'?'Latest result announcements':'नवीनतम result announcements' }}</p></div><a href="#">→</a></div><div class="utility-card"><span>📖</span><div><h3>{{ $lang==='en'?'Syllabus':'Syllabus' }}</h3><p>{{ $lang==='en'?'Exam syllabus & preparation':'परीक्षा syllabus एवं तैयारी' }}</p></div><a href="#">→</a></div></div></section>

<section class="app-cta"><div class="container app-cta-inner"><div><span class="section-kicker">🔔 CGJobs Alerts</span><h2>{{ $lang==='en'?'Never Miss an Important Government Job Update':'कोई महत्वपूर्ण सरकारी नौकरी अपडेट मिस न करें' }}</h2><p>{{ $lang==='en'?'Get new jobs, admit cards and results on your device.':'नई jobs, admit cards और results सीधे अपने device पर पाएं।' }}</p><div class="cta-actions"><a class="btn btn-light" href="{{ route('notifications',['lang'=>$lang]) }}">🔔 {{ $lang==='en'?'Enable Notifications':'Notifications चालू करें' }}</a><a class="btn btn-outline-light" href="https://play.google.com/store">📱 {{ $lang==='en'?'Get CGJobs App':'CGJobs App पाएं' }}</a></div></div><div class="stats"><div><b>10K+</b><span>{{ $lang==='en'?'Updates':'Updates' }}</span></div><div><b>50+</b><span>{{ $lang==='en'?'Departments':'Departments' }}</span></div><div><b>100%</b><span>{{ $lang==='en'?'Free':'Free' }}</span></div></div></div></section>
@endsection
