<?php

use App\Http\Controllers\Admin\AlertController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CacheController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\JobAdvancedController;
use App\Http\Controllers\Admin\JobManagementController;
use App\Http\Controllers\Admin\JobPosterTemplateController;
use App\Http\Controllers\Admin\JobSourceController;
use App\Http\Controllers\Admin\CanonicalJobImportController;
use App\Http\Controllers\Admin\QueuedJobSourceController;
use App\Http\Controllers\Admin\NewsSyncController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\StaticGkController;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\JobApplyRedirectController;
use App\Http\Controllers\Web\JobPosterController;
use App\Http\Controllers\Web\NotificationController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/jobs', [HomeController::class, 'jobs'])->name('listing.jobs');
Route::get('/current-affairs', [HomeController::class, 'currentAffairs'])->name('listing.current-affairs');
Route::get('/gk', [HomeController::class, 'staticGk'])->name('listing.gk');
Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications');
Route::get('/jobs/{id}/poster', [JobPosterController::class, 'show'])->name('job.poster');
Route::get('/jobs/{id}/apply', JobApplyRedirectController::class)->name('job.apply');
Route::get('/jobs/{id}', [HomeController::class, 'job'])->name('job.show');
Route::get('/current-affairs/{id}', [HomeController::class, 'job'])->name('current-affairs.show');
Route::get('/gk/{id}', [HomeController::class, 'gk'])->name('gk.show');
Route::get('/sitemap.xml', [HomeController::class, 'sitemap'])->name('sitemap');
Route::get('/robots.txt', [HomeController::class, 'robots'])->name('robots');
Route::get('/admin/login', [AuthController::class, 'showLogin'])->name('admin.login');
Route::post('/admin/login', [AuthController::class, 'login'])->name('admin.login.submit');
Route::match(['get', 'post'], '/admin/logout', [AuthController::class, 'logout'])->name('admin.logout');
Route::prefix('admin')->name('admin.')->middleware('admin.auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard', [DashboardController::class, 'index']);
    Route::get('/jobs/dashboard', [JobManagementController::class, 'dashboard'])->name('jobs.dashboard');
    Route::get('/jobs/templates', [JobManagementController::class, 'templates'])->name('jobs.templates');
    Route::post('/jobs/bulk-action', [JobManagementController::class, 'bulkAction'])->name('jobs.bulk-action');
    Route::post('/jobs/{job}/publish', [JobManagementController::class, 'publish'])->name('jobs.publish');
    Route::post('/jobs/{job}/republish', [JobManagementController::class, 'republish'])->name('jobs.republish');
    Route::get('/jobs/republished', [JobAdvancedController::class, 'republished'])->name('jobs.republished');
    Route::get('/jobs/categories', [JobAdvancedController::class, 'categories'])->name('jobs.categories');
    Route::get('/jobs/notifications', [JobAdvancedController::class, 'notifications'])->name('jobs.notifications');
    Route::get('/jobs/analytics', [JobAdvancedController::class, 'analytics'])->name('jobs.analytics');
    Route::get('/jobs/quality-checker', [JobAdvancedController::class, 'quality'])->name('jobs.quality');
    Route::get('/jobs/duplicate-detection', [JobAdvancedController::class, 'duplicates'])->name('jobs.duplicates');
    Route::get('/jobs/import-sync', [JobAdvancedController::class, 'importSync'])->name('jobs.import-sync');
    Route::get('/jobs/{job}/versions', [JobAdvancedController::class, 'versions'])->name('jobs.versions');
    Route::get('/jobs/{job}/timeline', [JobAdvancedController::class, 'timeline'])->name('jobs.timeline');
    Route::get('/jobs/{job}/documents', [JobAdvancedController::class, 'documents'])->name('jobs.documents');
    Route::post('/jobs/{job}/documents', [JobAdvancedController::class, 'storeDocument'])->name('jobs.documents.store');
    Route::get('/jobs/{job}/seo', [JobAdvancedController::class, 'seo'])->name('jobs.seo');
    Route::put('/jobs/{job}/seo', [JobAdvancedController::class, 'updateSeo'])->name('jobs.seo.update');
    Route::get('/jobs/{job}/notifications', [JobAdvancedController::class, 'notificationHistory'])->name('jobs.notification-history');
    Route::delete('/job-documents/{document}', [JobAdvancedController::class, 'destroyDocument'])->name('jobs.documents.destroy');
    Route::resource('jobs', JobManagementController::class);
    Route::resource('static-gk', StaticGkController::class);
    Route::get('/job-sources', [JobSourceController::class, 'index'])->name('job-sources.index');
    Route::post('/job-sources', [JobSourceController::class, 'store'])->name('job-sources.store');
    Route::put('/job-sources/{jobSource}', [JobSourceController::class, 'update'])->name('job-sources.update');
    Route::post('/job-sources/{jobSource}/toggle-notify', [JobSourceController::class, 'toggleNotify'])->name('job-sources.toggle-notify');
    Route::delete('/job-sources/{jobSource}', [JobSourceController::class, 'destroy'])->name('job-sources.destroy');
    Route::post('/job-sources/{jobSource}/sync', [QueuedJobSourceController::class, 'sync'])->name('job-sources.sync');
    Route::post('/job-sources/{jobSource}/refresh-pending', [QueuedJobSourceController::class, 'refreshPending'])->name('job-sources.refresh-pending');
    Route::get('/job-imports/{jobImport}/edit', [CanonicalJobImportController::class, 'edit'])->name('job-imports.edit');
    Route::put('/job-imports/{jobImport}', [CanonicalJobImportController::class, 'update'])->name('job-imports.update');
    Route::post('/job-imports/approve-all', [JobSourceController::class, 'approveAll'])->name('job-imports.approve-all');
    Route::post('/job-imports/{jobImport}/approve', [JobSourceController::class, 'approve'])->name('job-sources.approve');
    Route::post('/job-imports/{jobImport}/reject', [JobSourceController::class, 'reject'])->name('job-sources.reject');
    Route::post('/job-poster-template', [JobPosterTemplateController::class, 'upload'])->name('job-poster-template.upload');
    Route::resource('categories', CategoryController::class);
    Route::resource('sections', SectionController::class);
    Route::resource('alerts', AlertController::class);
    Route::get('/settings', [SettingController::class, 'index'])->name('settings.index');
    Route::post('/settings', [SettingController::class, 'update'])->name('settings.update');
    Route::get('/news-sync', [NewsSyncController::class, 'index'])->name('sync.index');
    Route::post('/news-sync', [NewsSyncController::class, 'sync'])->name('sync.run');
    Route::post('/news-sync/run', [NewsSyncController::class, 'sync'])->name('news-sync');
    Route::post('/cache/clear', [CacheController::class, 'clear'])->name('cache.clear');
});
