@extends('layouts.admin')
@section('title','View News')
@section('content')
<div class="flex items-center justify-between mb-5"><div><h2 class="text-2xl font-bold">News Preview</h2><p class="text-sm text-slate-500">Review source and AI-generated website/app content before publishing.</p></div><div class="flex gap-2"><a href="{{route('admin.news.index',['stage'=>$ai && in_array($ai->status,['generated','published'])?'processed':'fetched'])}}" class="px-3 py-2 rounded-xl bg-white border text-sm">Back</a><a href="{{route('admin.news.edit',$news)}}" class="px-3 py-2 rounded-xl bg-blue-700 text-white text-sm">Edit</a></div></div>
<div class="grid lg:grid-cols-3 gap-5">
 <div class="lg:col-span-2 space-y-5">
  <article class="bg-white rounded-2xl border p-6"><div class="text-xs text-slate-500 mb-2">{{$news->source}} · {{$news->published_at?->format('d M Y H:i')}}</div><h1 class="text-2xl font-bold">{{$news->title}}</h1>@if($news->image_url)<img src="{{$news->image_url}}" class="w-full max-h-80 object-cover rounded-xl mt-4" alt="">@endif<div class="mt-5 prose max-w-none">{!! nl2br(e($news->content ?: $news->summary)) !!}</div></article>
  @if($ai && $ai->generated_content)<article class="bg-white rounded-2xl border p-6"><div class="flex items-center justify-between mb-4"><h2 class="font-bold text-lg">AI Website Article</h2><span class="px-2 py-1 rounded-lg bg-blue-50 text-blue-700 text-xs">{{$ai->status}}</span></div><h3 class="text-xl font-bold">{{$ai->generated_content['website']['title'] ?? $news->title}}</h3><div class="mt-4 prose max-w-none">{!! nl2br(e($ai->generated_content['website']['content'] ?? '')) !!}</div></article><article class="bg-white rounded-2xl border p-6"><h2 class="font-bold text-lg mb-3">App / Mobile Version</h2><p>{{ $ai->generated_content['mobile']['summary'] ?? '' }}</p>@if(!empty($ai->generated_content['why_in_news']))<h3 class="font-semibold mt-4">Why in Current Affairs</h3><p>{{is_string($ai->generated_content['why_in_news'])?$ai->generated_content['why_in_news']:json_encode($ai->generated_content['why_in_news'])}}</p>@endif</article>@endif
 </div>
 <aside class="space-y-4"><div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-3">Classification</h3><div class="text-sm"><div class="text-slate-500">Category</div><div class="font-semibold mt-1">{{$news->category}}</div><div class="text-slate-500 mt-3">Exam relevance</div><div class="font-semibold mt-1">{{$news->exam_relevance}} / 5</div><div class="text-slate-500 mt-3">Status</div><div class="font-semibold mt-1">{{$news->status}}</div></div></div>@if($news->original_url)<div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-2">Original Source</h3><a href="{{$news->original_url}}" target="_blank" rel="noopener" class="text-blue-600 text-sm break-all">Open original article ↗</a></div>@endif @if($ai && $ai->generated_content)<div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-2">SEO</h3><div class="text-sm"><b>Title:</b> {{$ai->generated_content['seo']['title'] ?? ''}}<br><br><b>Description:</b> {{$ai->generated_content['seo']['description'] ?? ''}}<br><br><b>Focus keyword:</b> {{$ai->generated_content['seo']['focus_keyword'] ?? ''}}</div></div>@endif</aside>
</div>
@endsection
