@extends('layouts.admin')
@section('title','View News')
@section('content')
<div class="flex flex-wrap items-center justify-between gap-3 mb-5"><div><h2 class="text-2xl font-bold">News Preview</h2><p class="text-sm text-slate-500">One news record contains the website article and the mobile/app version.</p></div><div class="flex gap-2"><a href="{{route('admin.news.index',['stage'=>$news->status==='published'||$news->status==='archived'?'all':($ai?'processed':'fetched')])}}" class="px-3 py-2 rounded-xl bg-white border text-sm">← Back</a><a href="{{route('admin.news.edit',$news)}}" class="px-3 py-2 rounded-xl bg-blue-700 text-white text-sm">Edit</a></div></div>
<div class="grid lg:grid-cols-3 gap-5">
 <div class="lg:col-span-2 space-y-5">
  <article class="bg-white rounded-2xl border p-6"><div class="text-xs text-slate-500 mb-2">{{$news->source}} · {{$news->published_at?->format('d M Y H:i')}}</div><h1 class="text-2xl font-bold">{{$news->title}}</h1>@if($news->image_url)<img src="{{$news->image_url}}" class="w-full max-h-80 object-cover rounded-xl mt-4" alt="">@endif<div class="mt-5 prose max-w-none">{!! nl2br(e($news->content ?: $news->summary)) !!}</div></article>
  @if($ai && $ai->generated_content)
  <article class="bg-white rounded-2xl border p-6"><div class="flex items-center justify-between mb-4"><h2 class="font-bold text-lg">Website Version</h2><span class="px-2 py-1 rounded-lg bg-blue-50 text-blue-700 text-xs">{{$ai->status}}</span></div><h3 class="text-xl font-bold">{{$ai->generated_content['website']['title'] ?? $news->title}}</h3><p class="text-sm text-slate-500 mt-2">SEO: {{$ai->generated_content['seo']['title'] ?? ''}}</p><div class="mt-4 prose max-w-none">{!! nl2br(e($ai->generated_content['website']['content'] ?? '')) !!}</div></article>
  <article class="bg-white rounded-2xl border p-6"><h2 class="font-bold text-lg mb-2">Mobile / App Version</h2><div class="text-xs text-slate-500 mb-3">Short current-affairs format for the app</div><h3 class="font-bold">{{$ai->generated_content['mobile']['title'] ?? $news->title}}</h3><p class="mt-3">{{ $ai->generated_content['mobile']['summary'] ?? '' }}</p>@if(!empty($ai->generated_content['key_facts']))<h3 class="font-semibold mt-4">Key Facts</h3><ul class="list-disc pl-5 mt-2">@foreach((array)$ai->generated_content['key_facts'] as $fact)<li>{{is_string($fact)?$fact:json_encode($fact)}}</li>@endforeach</ul>@endif @if(!empty($ai->generated_content['why_in_news']))<h3 class="font-semibold mt-4">Why in Current Affairs</h3><p>{{is_string($ai->generated_content['why_in_news'])?$ai->generated_content['why_in_news']:json_encode($ai->generated_content['why_in_news'])}}</p>@endif</article>
  @endif
 </div>
 <aside class="space-y-4">
  <div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-3">Publication</h3><div class="text-sm space-y-2"><div>Status: <b>{{ucfirst($news->status)}}</b></div><div>Website: <b class="{{ $news->published_web?'text-emerald-600':'text-slate-400' }}">{{ $news->published_web?'Published':'Unpublished' }}</b></div><div>Mobile/App: <b class="{{ $news->published_mobile?'text-emerald-600':'text-slate-400' }}">{{ $news->published_mobile?'Published':'Unpublished' }}</b></div></div>
   <div class="grid grid-cols-2 gap-2 mt-4">
    <form method="POST" action="{{route('admin.news.channel',$news)}}">@csrf<input type="hidden" name="channel" value="web"><input type="hidden" name="action" value="{{$news->published_web?'unpublish':'publish'}}"><button class="w-full px-2 py-2 rounded-lg {{ $news->published_web?'bg-amber-50 text-amber-700':'bg-blue-600 text-white' }} text-xs font-semibold">{{$news->published_web?'Unpublish Web':'Publish Web'}}</button></form>
    <form method="POST" action="{{route('admin.news.channel',$news)}}">@csrf<input type="hidden" name="channel" value="mobile"><input type="hidden" name="action" value="{{$news->published_mobile?'unpublish':'publish'}}"><button class="w-full px-2 py-2 rounded-lg {{ $news->published_mobile?'bg-amber-50 text-amber-700':'bg-purple-600 text-white' }} text-xs font-semibold">{{$news->published_mobile?'Unpublish App':'Publish App'}}</button></form>
   </div>
   @if($news->status==='published')<form method="POST" action="{{route('admin.news.archive',$news)}}" class="mt-2">@csrf<button class="w-full px-3 py-2 rounded-lg bg-slate-100 text-slate-700 text-xs font-semibold">Archive</button></form>@elseif($news->status==='archived' && $ai)<form method="POST" action="{{route('admin.news.channel',$news)}}" class="mt-2">@csrf<input type="hidden" name="channel" value="web"><input type="hidden" name="action" value="publish"><button class="w-full px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-semibold">Republish Web</button></form>@endif
  </div>
  <div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-3">Classification</h3><div class="text-sm"><div class="text-slate-500">Category</div><div class="font-semibold mt-1">{{$news->category}}</div><div class="text-slate-500 mt-3">Exam relevance</div><div class="font-semibold mt-1">{{$news->exam_relevance}} / 5</div></div></div>
  @if($news->original_url)<div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-2">Original Source</h3><a href="{{$news->original_url}}" target="_blank" rel="noopener" class="text-blue-600 text-sm break-all">Open original article ↗</a></div>@endif
  @if($ai && $ai->generated_content)<div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-2">SEO</h3><div class="text-sm"><b>Title:</b> {{$ai->generated_content['seo']['title'] ?? ''}}<br><br><b>Description:</b> {{$ai->generated_content['seo']['description'] ?? ''}}<br><br><b>Focus keyword:</b> {{$ai->generated_content['seo']['focus_keyword'] ?? ''}}</div></div>@endif
 </aside>
</div>
@endsection
