<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Job;
use App\Models\JobImport;
use App\Services\GeminiService;
use App\Services\JobBatchAiService;
use App\Services\JobPublishNotificationService;
use App\Services\JobScrapers\ErojgarScraper;
use App\Services\UnifiedJobScraperPipeline;
use Illuminate\Http\Request;

class JobScraperConsoleController extends Controller
{
    private const CATEGORIES = ['CGPSC', 'CGSSB', 'CONTRACTUAL', 'CENTRAL GOVT'];
    private const SUBCATEGORIES = [
        'Education', 'Health', 'PWD', 'CSEB', 'Police', 'Revenue',
        'Panchayat', 'Agriculture', 'Judiciary', 'Banking', 'General'
    ];

    public function index(Request $request)
    {
        $geminiService = app(GeminiService::class);
        $isGeminiReady = $geminiService->isConfigured();

        // Staged items (scraped raw items awaiting review / Gemini transformation)
        $stagedItems = JobImport::where('status', 'staged')
            ->latest()
            ->paginate(30, ['*'], 'staged_page');

        // Recent draft jobs generated by Gemini
        $draftJobs = Job::where(fn($q) => $q->where('section', 'jobs')->orWhereNull('section'))
            ->where('workflow_status', 'draft')
            ->latest('updated_at')
            ->paginate(15, ['*'], 'drafts_page');

        $districts = ErojgarScraper::$chhattisgarhDistricts;

        return view('admin.jobs.scraper-console', [
            'stagedItems' => $stagedItems,
            'draftJobs' => $draftJobs,
            'districts' => $districts,
            'isGeminiReady' => $isGeminiReady,
            'categories' => self::CATEGORIES,
            'subcategories' => self::SUBCATEGORIES,
        ]);
    }

    /**
     * Run scraper for selected sources and filters
     */
    public function runScrape(Request $request, UnifiedJobScraperPipeline $pipeline)
    {
        $sources = $request->input('sources', ['cgpsc', 'vyapam', 'erojgar', 'central_govt', 'jobskind']);
        $postTypes = $request->input('post_types', ['job']);
        $district = $request->input('district', 'All');
        $from = $request->input('from');
        $to = $request->input('to');

        try {
            $result = $pipeline->scrapeAndStage([
                'sources' => $sources,
                'post_types' => $postTypes,
                'district' => $district,
                'from' => $from,
                'to' => $to,
            ]);

            return back()->with('success', "Scraping complete: {$result['fetched']} notices discovered, {$result['staged']} new notices staged in the review grid, {$result['skipped']} duplicates skipped.");
        } catch (\Throwable $e) {
            report($e);
            return back()->withErrors(['scrape' => 'Scraper failed: ' . $e->getMessage()]);
        }
    }

    /**
     * Delete selected or all staged raw notices
     */
    public function deleteStaged(Request $request)
    {
        if ($request->has('clear_all')) {
            $count = JobImport::where('status', 'staged')->delete();
            return back()->with('success', "Cleared all {$count} staged items from review grid.");
        }

        $ids = $request->input('selected_ids', []);
        if (empty($ids)) {
            return back()->withErrors(['selected' => 'Please select at least one item to delete.']);
        }

        $count = JobImport::whereIn('id', $ids)->where('status', 'staged')->delete();
        return back()->with('success', "Deleted {$count} selected notices from staging.");
    }

    /**
     * Send selected items to Gemini in a SINGLE BATCH API CALL
     */
    public function processBatchGemini(Request $request, JobBatchAiService $aiService)
    {
        $ids = $request->input('selected_ids', []);
        if (empty($ids)) {
            return back()->withErrors(['selected' => 'Please select at least one staged notice to process with Gemini.']);
        }

        $imports = JobImport::whereIn('id', $ids)->where('status', 'staged')->get();
        if ($imports->isEmpty()) {
            return back()->withErrors(['selected' => 'No valid staged notices found for processing.']);
        }

        // Format batch payload
        $items = [];
        foreach ($imports as $import) {
            $items[] = [
                'id' => $import->id,
                'category' => $import->job_category ?: 'CGSSB',
                'title' => $import->title,
                'raw_content' => $import->summary ?: $import->content,
                'source_name' => $import->published_by ?: 'CG Official Portal',
            ];
        }

        $result = $aiService->processBatch($items);

        if (!$result['success']) {
            return back()->withErrors(['gemini' => $result['message'] ?? 'Gemini batch processing failed.']);
        }

        $processedData = $result['processed'] ?? [];
        $indexedAiData = [];
        foreach ($processedData as $row) {
            if (isset($row['id'])) {
                $indexedAiData[$row['id']] = $row;
            }
        }

        $createdJobsCount = 0;
        foreach ($imports as $import) {
            $aiData = $indexedAiData[$import->id] ?? null;
            if ($aiData) {
                $job = $aiService->createOrUpdateJobRecord($import, $aiData);
                $import->update([
                    'status' => 'processed',
                    'job_id' => $job->id,
                    'processed_at' => now(),
                ]);
                $createdJobsCount++;
            }
        }

        return back()->with('success', "Successfully analyzed {$createdJobsCount} jobs with Gemini in 1 single API call! Structured Drafts are now ready below for review and publishing.");
    }

    /**
     * Publish a draft job to make it live
     */
    public function publishJob(Request $request, Job $job, JobPublishNotificationService $notifier)
    {
        $job->update([
            'workflow_status' => 'published',
            'published_at' => now()->format('Y-m-d'),
        ]);

        if ($request->boolean('send_notification')) {
            try {
                $import = JobImport::where('job_id', $job->id)->first();
                if ($import) {
                    $notifier->notify($import, $job);
                }
            } catch (\Throwable $e) {
                // Log and continue
            }
        }

        return back()->with('success', "Job '{$job->title}' is now LIVE on the website and mobile app!");
    }

    /**
     * Schedule a draft job for future publication
     */
    public function scheduleJob(Request $request, Job $job)
    {
        $data = $request->validate([
            'scheduled_at' => 'required|date|after:now',
        ]);

        $job->update([
            'workflow_status' => 'scheduled',
            'scheduled_at' => $data['scheduled_at'],
        ]);

        return back()->with('success', "Job scheduled to go live on {$job->scheduled_at}.");
    }

    /**
     * Delete a draft job
     */
    public function deleteDraft(Job $job)
    {
        $job->delete();
        return back()->with('success', 'Draft job deleted.');
    }
}
