@extends('layouts.admin')
@section('title','Create New Job')
@section('content')
<div class="max-w-5xl mx-auto space-y-6"><div class="flex items-end justify-between gap-3"><div><h2 class="text-xl font-black text-slate-900">Create New Job</h2><p class="text-xs text-slate-500 mt-1">Draft, publish now, or schedule automatic publishing. No paid AI is required.</p></div><a href="{{ route('admin.jobs.templates') }}" class="px-3 py-2 border rounded-xl text-xs font-bold">Templates</a></div>
<form method="POST" action="{{ route('admin.jobs.store') }}" class="bg-white rounded-3xl border shadow-sm p-6 sm:p-8 space-y-6">@csrf
<div class="grid md:grid-cols-4 gap-4 bg-slate-50 p-4 rounded-2xl"><div><label class="label">Main Category *</label><select name="job_category" id="job_category" required class="input">@foreach($jobCategories as $c)<option value="{{ $c }}" @selected(request('job_category',old('job_category','CGSSB'))===$c)>{{ $c }}</option>@endforeach</select></div><div><label class="label">Department *</label><select name="department" id="department" required class="input">@foreach($departments as $d)<option value="{{ $d }}" @selected(request('department',old('department'))===$d)>{{ $d }}</option>@endforeach</select></div><div><label class="label">Post Type</label><select name="post_type" class="input">@foreach($postTypes as $v=>$label)<option value="{{ $v }}">{{ $label }}</option>@endforeach</select></div><div><label class="label">Workflow</label><select name="workflow_status" id="workflow_status" class="input"><option value="published">Publish Now</option><option value="draft">Save Draft</option><option value="scheduled">Schedule</option></select></div><input type="hidden" name="section" value="jobs"></div>
<div id="scheduleBox" class="hidden bg-blue-50 border border-blue-100 rounded-2xl p-4"><label class="label">Publish Date & Time *</label><input type="datetime-local" name="scheduled_at" class="input"></div>
<div class="grid md:grid-cols-3 gap-5"><div class="md:col-span-2"><label class="label">Job Name *</label><input name="title" value="{{ old('title') }}" required class="input" placeholder="Lab Assistant Recruitment 2026"></div><div><label class="label">Released By / Organization</label><input name="source" value="{{ old('source') }}" class="input" placeholder="CGSSB / CGPSC / SSC"></div></div>
<div class="grid md:grid-cols-4 gap-4"><div><label class="label">Total Posts</label><input name="vacancies" value="{{ old('vacancies') }}" class="input"></div><div><label class="label">Apply From</label><input name="application_start" value="{{ old('application_start') }}" class="input"></div><div><label class="label">Last Date</label><input name="last_date" value="{{ old('last_date') }}" class="input"></div><div><label class="label">Exam Date</label><input name="exam_date" value="{{ old('exam_date') }}" class="input"></div></div>
<div class="grid md:grid-cols-4 gap-4"><div><label class="label">Admit Card Date</label><input name="admit_card_date" value="{{ old('admit_card_date') }}" class="input"></div><div><label class="label">Result Date</label><input name="result_date" value="{{ old('result_date') }}" class="input"></div><div><label class="label">Age Limit</label><input name="age_limit" value="{{ old('age_limit') }}" class="input"></div><div><label class="label">Salary</label><input name="salary" value="{{ old('salary') }}" class="input"></div></div>
<div><label class="label">Eligibility</label><input name="eligibility" value="{{ old('eligibility') }}" class="input"></div><div><label class="label">Selection Process</label><input name="selection_process" value="{{ old('selection_process') }}" class="input"></div><div><label class="label">Short Summary *</label><textarea name="summary" rows="3" required class="input">{{ old('summary') }}</textarea></div><div><label class="label">Detailed Information</label><textarea name="detailed_content" rows="8" class="input"></textarea></div>
<div class="grid md:grid-cols-2 gap-5"><div><label class="label">Official Notification URL</label><input type="url" name="official_notification_url" value="{{ old('official_notification_url') }}" class="input"></div><div><label class="label">Apply Online URL</label><input type="url" name="apply_url" value="{{ old('apply_url') }}" class="input"></div><div><label class="label">Source URL</label><input type="url" name="source_url" value="{{ old('source_url') }}" class="input"></div><div><label class="label">Source Image URL</label><input type="url" name="image_url" value="{{ old('image_url') }}" class="input"></div></div>
<div class="flex flex-wrap gap-6 border-t pt-4"><label class="check"><input type="checkbox" name="is_breaking" value="1"> HOT / Breaking</label><label class="check"><input type="checkbox" name="is_new" value="1" checked> New</label><label class="check"><input type="checkbox" name="broadcast_push" value="1" checked> Push notification on publish</label></div>
<div class="flex justify-end"><button id="submitBtn" class="px-6 py-3 rounded-xl bg-brand-600 text-white font-black">Publish Job</button></div>
</form></div>
<style>.label{display:block;font-size:11px;font-weight:800;color:#475569;margin-bottom:6px;text-transform:uppercase;letter-spacing:.04em}.input{width:100%;border:1px solid #dbe2ea;border-radius:12px;padding:11px 13px;background:#fff;font-size:14px;outline:none}.check{font-size:13px;font-weight:700;color:#475569;display:flex;gap:8px;align-items:center}</style>
<script>const w=document.getElementById('workflow_status'),b=document.getElementById('scheduleBox'),s=document.getElementById('submitBtn');function sync(){b.classList.toggle('hidden',w.value!=='scheduled');s.textContent=w.value==='draft'?'Save Draft':(w.value==='scheduled'?'Schedule Job':'Publish Job')}w.addEventListener('change',sync);sync();</script>
@endsection
