@extends('layouts.admin')
@section('title',$title)
@section('content')
<div class="flex items-center justify-between mb-6"><div><h2 class="text-2xl font-bold">{{$title}}</h2><p class="text-sm text-slate-500 mt-1">Advanced Jobs Management Center</p></div><a href="{{route('admin.jobs.index',['section'=>'jobs'])}}" class="px-4 py-2 rounded-xl bg-slate-800 text-white text-sm">All Jobs</a></div>
@if($mode==='republished')
<div class="bg-white rounded-2xl border overflow-hidden"><div class="p-4 border-b font-semibold">Republished Jobs</div><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-left">Job</th><th class="p-3">Category</th><th class="p-3">Published</th><th class="p-3"></th></tr></thead><tbody>@forelse($jobs as $job)<tr class="border-t"><td class="p-3 font-medium">{{$job->title}}</td><td class="p-3">{{$job->job_category}} → {{$job->department}}</td><td class="p-3">{{$job->published_at}}</td><td class="p-3"><a class="text-blue-600" href="{{route('admin.jobs.edit',$job)}}">Edit</a></td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">No republished jobs yet.</td></tr>@endforelse</tbody></table><div class="p-4">{{$jobs->links()}}</div></div>
@elseif($mode==='categories')
<div class="grid md:grid-cols-2 gap-5"><div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-4">Main Categories</h3>@foreach($categories as $c)<div class="flex justify-between py-3 border-b last:border-0"><span>{{$c}}</span><b>{{($categoryCounts[$c]->total??0)}}</b></div>@endforeach</div><div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-4">Departments</h3>@foreach($departments as $d)<div class="flex justify-between py-3 border-b last:border-0"><span>{{$d->department}}</span><b>{{$d->total}}</b></div>@endforeach</div></div>
@elseif($mode==='notifications' || $mode==='notification-history')
@if($mode==='notification-history')<div class="bg-white rounded-2xl border p-5 mb-5"><h3 class="font-bold">{{$job->title}}</h3><p class="text-sm text-slate-500">Notification history</p></div>@endif<div class="bg-white rounded-2xl border overflow-hidden"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-left">Type</th><th class="p-3 text-left">Title</th><th class="p-3">Broadcasted</th><th class="p-3">Time</th></tr></thead><tbody>@forelse($alerts as $a)<tr class="border-t"><td class="p-3 font-medium">{{$a->type}}</td><td class="p-3">{{$a->title}}</td><td class="p-3">{{$a->is_broadcasted?'Yes':'No'}}</td><td class="p-3">{{$a->created_at}}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center">No notification history.</td></tr>@endforelse</tbody></table><div class="p-4">{{$alerts->links()}}</div></div>
@elseif($mode==='versions')
<div class="space-y-4">@forelse($versions as $v)<div class="bg-white rounded-2xl border p-5"><div class="flex justify-between"><b>{{ucfirst($v->action)}}</b><span class="text-xs text-slate-500">{{$v->created_at}}</span></div><pre class="mt-3 text-xs bg-slate-50 rounded-xl p-3 overflow-auto max-h-72">{{json_encode($v->snapshot,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)}}</pre></div>@empty<div class="bg-white rounded-2xl border p-8 text-center">No versions recorded.</div>@endforelse</div><div class="mt-4">{{$versions->links()}}</div>
@elseif($mode==='timeline')
<div class="bg-white rounded-2xl border p-6"><h3 class="font-bold mb-6">{{$job->title}}</h3><div class="space-y-6">@foreach($events as $e)<div class="flex gap-4"><div class="w-3 h-3 rounded-full bg-blue-600 mt-1.5"></div><div><b>{{$e['title']}}</b><div class="text-sm text-slate-500">{{$e['date']}}</div><p class="text-sm mt-1">{{$e['detail']}}</p></div></div>@endforeach</div></div>
@elseif($mode==='documents')
<div class="grid lg:grid-cols-3 gap-5"><div class="lg:col-span-2 bg-white rounded-2xl border overflow-hidden"><div class="p-4 border-b font-semibold">Official Documents</div>@forelse($documents as $d)<div class="p-4 border-b flex justify-between items-center"><div><b>{{$d->title}}</b><p class="text-xs text-slate-500">{{$d->document_type}}</p></div><div class="flex gap-3"><a target="_blank" class="text-blue-600" href="{{$d->url}}">Open</a><form method="POST" action="{{route('admin.jobs.documents.destroy',$d)}}">@csrf @method('DELETE')<button class="text-rose-600">Delete</button></form></div></div>@empty<div class="p-8 text-center text-slate-500">No documents added.</div>@endforelse</div><form method="POST" action="{{route('admin.jobs.documents.store',$job)}}" class="bg-white rounded-2xl border p-5 space-y-3">@csrf<h3 class="font-bold">Add Document</h3><input name="title" required placeholder="Document title" class="w-full border rounded-xl p-2.5"><select name="document_type" class="w-full border rounded-xl p-2.5"><option value="notification">Notification</option><option value="syllabus">Syllabus</option><option value="answer_key">Answer Key</option><option value="other">Other</option></select><input name="url" type="url" required placeholder="https://..." class="w-full border rounded-xl p-2.5"><button class="w-full bg-blue-700 text-white rounded-xl py-2.5">Add Document</button></form></div>
@elseif($mode==='seo')
<form method="POST" action="{{route('admin.jobs.seo.update',$job)}}" class="bg-white rounded-2xl border p-6 space-y-4">@csrf @method('PUT')<h3 class="font-bold text-lg">{{$job->title}}</h3><div><label class="text-sm font-medium">SEO Title</label><input name="seo_title" value="{{$job->seo_title}}" maxlength="255" class="w-full border rounded-xl p-3 mt-1"></div><div><label class="text-sm font-medium">Meta Description</label><textarea name="seo_description" maxlength="500" class="w-full border rounded-xl p-3 mt-1" rows="3">{{$job->seo_description}}</textarea></div><div><label class="text-sm font-medium">Keywords</label><input name="seo_keywords" value="{{$job->seo_keywords}}" class="w-full border rounded-xl p-3 mt-1"></div><div><label class="text-sm font-medium">Canonical URL</label><input name="canonical_url" value="{{$job->canonical_url}}" type="url" class="w-full border rounded-xl p-3 mt-1"></div><button class="bg-blue-700 text-white px-5 py-2.5 rounded-xl">Save SEO</button></form>
@elseif($mode==='quality')
<div class="bg-white rounded-2xl border overflow-hidden"><table class="w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-left">Job</th><th class="p-3">Category</th><th class="p-3">Quality Score</th><th class="p-3"></th></tr></thead><tbody>@foreach($jobs as $job)<tr class="border-t"><td class="p-3">{{$job->title}}</td><td class="p-3">{{$job->job_category}} → {{$job->department}}</td><td class="p-3"><span class="font-bold {{$scores[$job->id]>=80?'text-emerald-600':($scores[$job->id]>=60?'text-amber-600':'text-rose-600')}}">{{$scores[$job->id]}}%</span></td><td class="p-3"><a href="{{route('admin.jobs.edit',$job)}}" class="text-blue-600">Fix</a></td></tr>@endforeach</tbody></table><div class="p-4">{{$jobs->links()}}</div></div>
@elseif($mode==='duplicates')
<div class="space-y-4">@forelse($groups as $key=>$group)<div class="bg-white rounded-2xl border p-5"><h3 class="font-bold mb-3">Possible duplicate group</h3>@foreach($group as $job)<div class="flex justify-between py-2 border-b last:border-0"><span>{{$job->title}} <span class="text-xs text-slate-400">#{{$job->id}}</span></span><span class="text-xs">{{$job->job_category}} → {{$job->department}}</span></div>@endforeach</div>@empty<div class="bg-white rounded-2xl border p-8 text-center text-emerald-700">No exact-title duplicate groups found.</div>@endforelse</div>
@elseif($mode==='analytics')
<div class="grid sm:grid-cols-2 lg:grid-cols-5 gap-4 mb-6">@foreach($stats as $k=>$v)<div class="bg-white rounded-2xl border p-5"><div class="text-xs uppercase text-slate-400">{{str_replace('_',' ',$k)}}</div><div class="text-2xl font-bold mt-1">{{number_format($v)}}</div></div>@endforeach</div><div class="grid lg:grid-cols-2 gap-5"><div class="bg-white rounded-2xl border overflow-hidden"><div class="p-4 font-semibold border-b">By Category</div><table class="w-full text-sm"><tbody>@foreach($byCategory as $r)<tr class="border-b"><td class="p-3">{{$r->job_category}}</td><td class="p-3">{{$r->total}} jobs</td><td class="p-3">{{$r->views}} views</td><td class="p-3">{{$r->clicks}} clicks</td></tr>@endforeach</tbody></table></div><div class="bg-white rounded-2xl border overflow-hidden"><div class="p-4 font-semibold border-b">Monthly Performance</div><table class="w-full text-sm"><tbody>@foreach($byMonth as $r)<tr class="border-b"><td class="p-3">{{$r->month}}</td><td class="p-3">{{$r->total}} jobs</td><td class="p-3">{{$r->views}} views</td><td class="p-3">{{$r->clicks}} clicks</td></tr>@endforeach</tbody></table></div></div>
@endif
@endsection