@extends('layouts.admin')
@section('title','Create New Job')
@section('content')
<div class="max-w-6xl mx-auto space-y-6">
<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h2 class="text-2xl font-black text-slate-900">Create New Job</h2><p class="text-xs text-slate-500 mt-1">Create a complete recruitment record with media, source links, content and publishing workflow.</p></div><a href="{{ route('admin.jobs.index',['section'=>'jobs']) }}" class="px-4 py-2.5 border rounded-xl text-xs font-bold">← All Jobs</a></div>
<div class="grid grid-cols-2 md:grid-cols-5 gap-2"><div class="tab active">① Basic Information</div><div class="tab">② Media & Source</div><div class="tab">③ Content & Details</div><div class="tab">④ SEO & Settings</div><div class="tab">⑤ Workflow & Publish</div></div>
<form method="POST" action="{{ route('admin.jobs.store') }}" class="bg-white rounded-3xl border shadow-sm overflow-hidden">@csrf
<div class="p-5 sm:p-7 space-y-7">
<section><div class="section-title">Basic Information</div><div class="grid md:grid-cols-4 gap-4"><div class="md:col-span-2"><label class="label">Job Title *</label><input name="title" value="{{ old('title') }}" required class="input" placeholder="Lab Assistant Recruitment 2026"></div><div><label class="label">Main Category *</label><select name="job_category" required class="input">@foreach($jobCategories as $c)<option value="{{ $c }}" @selected(request('job_category',old('job_category','CGSSB'))===$c)>{{ $c }}</option>@endforeach</select></div><div><label class="label">Department *</label><select name="department" required class="input">@foreach($departments as $d)<option value="{{ $d }}" @selected(request('department',old('department'))===$d)>{{ $d }}</option>@endforeach</select></div><div><label class="label">Post Type</label><select name="post_type" class="input">@foreach($postTypes as $v=>$label)<option value="{{ $v }}">{{ $label }}</option>@endforeach</select></div><div><label class="label">Total Posts</label><input name="vacancies" value="{{ old('vacancies') }}" class="input" placeholder="50"></div><div><label class="label">Job Location</label><input name="category" value="{{ old('category') }}" class="input" placeholder="Chhattisgarh"></div><div><label class="label">Released By / Organization</label><input name="source" value="{{ old('source') }}" class="input" placeholder="CGSSB / CGPSC / SSC"></div></div></section>
<section><div class="section-title">Media & Source</div><div class="grid lg:grid-cols-2 gap-5"><div><label class="label">Main Image URL</label><input id="image_url" type="url" name="image_url" value="{{ old('image_url') }}" class="input" placeholder="https://example.com/job-poster.jpg"><p class="hint">Use the crawler source image when available. Preview updates automatically.</p></div><div class="rounded-2xl border bg-slate-50 p-3"><div class="label">Image Preview</div><div class="h-44 rounded-xl bg-white border flex items-center justify-center overflow-hidden"><img id="imagePreview" src="{{ old('image_url') }}" alt="Main image preview" class="max-h-full max-w-full object-contain {{ old('image_url')?'':'hidden' }}"><span id="imageEmpty" class="text-xs text-slate-400 {{ old('image_url')?'hidden':'' }}">Paste a valid image URL to preview</span></div></div></div><div class="grid md:grid-cols-3 gap-4 mt-4"><div><label class="label">Source URL</label><input type="url" name="source_url" value="{{ old('source_url') }}" class="input"></div><div><label class="label">Official Notification URL</label><input type="url" name="official_notification_url" value="{{ old('official_notification_url') }}" class="input"></div><div><label class="label">Apply Online URL</label><input type="url" name="apply_url" value="{{ old('apply_url') }}" class="input"></div></div></section>
<section><div class="section-title">Dates & Recruitment Details</div><div class="grid md:grid-cols-4 gap-4"><div><label class="label">Apply From</label><input name="application_start" value="{{ old('application_start') }}" class="input" placeholder="dd-mm-yyyy"></div><div><label class="label">Last Date</label><input name="last_date" value="{{ old('last_date') }}" class="input" placeholder="dd-mm-yyyy"></div><div><label class="label">Exam Date</label><input name="exam_date" value="{{ old('exam_date') }}" class="input"></div><div><label class="label">Admit Card Date</label><input name="admit_card_date" value="{{ old('admit_card_date') }}" class="input"></div><div><label class="label">Result Date</label><input name="result_date" value="{{ old('result_date') }}" class="input"></div><div><label class="label">Age Limit</label><input name="age_limit" value="{{ old('age_limit') }}" class="input"></div><div><label class="label">Salary</label><input name="salary" value="{{ old('salary') }}" class="input"></div><div><label class="label">Selection Process</label><input name="selection_process" value="{{ old('selection_process') }}" class="input"></div></div></section>
<section><div class="section-title">Content & Details</div><div class="space-y-4"><div><label class="label">Eligibility</label><input name="eligibility" value="{{ old('eligibility') }}" class="input"></div><div><label class="label">Short Summary *</label><textarea name="summary" rows="4" required class="input" placeholder="Brief recruitment summary...">{{ old('summary') }}</textarea></div><div><label class="label">Detailed Information</label><textarea name="detailed_content" rows="10" class="input" placeholder="Full recruitment information, important dates, eligibility, selection process, application instructions..."></textarea></div></div></section>
<section><div class="section-title">Workflow & Publish</div><div class="grid lg:grid-cols-3 gap-5"><div class="lg:col-span-2 grid sm:grid-cols-3 gap-3"><label class="option"><input type="checkbox" name="is_breaking" value="1"> <span>🔥 Mark as HOT / Breaking</span></label><label class="option"><input type="checkbox" name="is_new" value="1" checked> <span>⭐ Mark as New</span></label><label class="option"><input type="checkbox" name="broadcast_push" value="1" checked> <span>🔔 Send Push Notification</span></label></div><div class="rounded-2xl bg-slate-50 border p-4"><label class="label">Publish Status</label><select name="workflow_status" id="workflow_status" class="input"><option value="published">Publish Now</option><option value="draft">Save as Draft</option><option value="scheduled">Schedule for Later</option></select></div></div><div id="scheduleBox" class="hidden mt-4 rounded-2xl bg-blue-50 border border-blue-100 p-4"><label class="label">Scheduled Publish Date & Time *</label><input type="datetime-local" name="scheduled_at" class="input"></div></section>
</div><div class="border-t bg-slate-50 px-5 sm:px-7 py-4 flex flex-col sm:flex-row justify-end gap-2"><button id="submitBtn" class="px-6 py-3 rounded-xl bg-brand-600 text-white font-black shadow-sm">Publish Job</button><button type="button" onclick="document.querySelector('#workflow_status').value='draft';document.querySelector('form').submit()" class="px-6 py-3 rounded-xl border bg-white font-bold">Save as Draft</button></div>
</form></div>
<style>.tab{padding:11px 12px;border:1px solid #e2e8f0;border-radius:13px;background:#fff;text-align:center;font-size:10px;font-weight:800;color:#64748b}.tab.active{color:#4f46e5;border-color:#c7d2fe;background:#eef2ff}.section-title{font-size:14px;font-weight:900;color:#0f172a;margin-bottom:14px;display:flex;align-items:center;gap:8px}.section-title:before{content:'';width:4px;height:18px;border-radius:5px;background:#6366f1}.label{display:block;font-size:10px;font-weight:800;color:#475569;margin-bottom:6px;text-transform:uppercase;letter-spacing:.04em}.input{width:100%;border:1px solid #dbe2ea;border-radius:12px;padding:11px 13px;background:#fff;font-size:13px;outline:none}.hint{font-size:10px;color:#94a3b8;margin-top:5px}.option{display:flex;gap:8px;align-items:center;border:1px solid #e2e8f0;border-radius:12px;padding:12px;background:#fff;font-size:11px;font-weight:800;color:#475569}.hidden{display:none}</style>
<script>const image=document.getElementById('image_url'),preview=document.getElementById('imagePreview'),empty=document.getElementById('imageEmpty');image?.addEventListener('input',()=>{const u=image.value.trim();preview.classList.toggle('hidden',!u);empty.classList.toggle('hidden',!!u);if(u)preview.src=u});preview?.addEventListener('error',()=>{preview.classList.add('hidden');empty.textContent='Image could not be loaded';empty.classList.remove('hidden')});const w=document.getElementById('workflow_status'),b=document.getElementById('scheduleBox'),s=document.getElementById('submitBtn');function sync(){const scheduled=w.value==='scheduled';b.classList.toggle('hidden',!scheduled);s.textContent=w.value==='draft'?'Save Draft':(scheduled?'Schedule Job':'Publish Job')}w.addEventListener('change',sync);sync();</script>
@endsection
