@extends('layouts.admin')
@section('title','Jobs Dashboard')
@section('content')
<div class="space-y-6">
  <div class="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3"><div><h2 class="text-2xl font-black text-slate-900">Jobs Dashboard</h2><p class="text-xs text-slate-500 mt-1">Recruitment control center — status, deadlines, notifications and performance.</p></div><div class="flex gap-2"><a href="{{ route('admin.jobs.templates') }}" class="px-4 py-2.5 bg-white border rounded-xl text-xs font-bold text-slate-700">Templates</a><a href="{{ route('admin.jobs.create') }}" class="px-4 py-2.5 bg-brand-600 text-white rounded-xl text-xs font-bold">+ Create Job</a></div></div>
  <div class="grid grid-cols-2 lg:grid-cols-5 gap-3">
    @foreach([['total','Total Jobs','fa-briefcase','slate'],['published','Published','fa-circle-check','emerald'],['drafts','Drafts','fa-file-pen','amber'],['scheduled','Scheduled','fa-clock','blue'],['archived','Archived','fa-box-archive','purple']] as [$k,$label,$icon,$tone])
      <a href="{{ route('admin.jobs.index',['section'=>'jobs','status'=>$k==='total'?'':$k]) }}" class="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm hover:shadow-md transition"><div class="flex items-center justify-between"><span class="text-[10px] font-black uppercase tracking-wider text-slate-400">{{ $label }}</span><i class="fa-solid {{ $icon }} text-{{ $tone }}-500"></i></div><div class="text-2xl font-black text-slate-900 mt-2">{{ number_format($stats[$k]) }}</div></a>
    @endforeach
  </div>
  <div class="grid grid-cols-2 lg:grid-cols-5 gap-3">
    <a href="{{ route('admin.jobs.index',['section'=>'jobs','deadline'=>'closing']) }}" class="bg-rose-50 border border-rose-100 rounded-2xl p-4"><div class="text-[10px] font-black uppercase text-rose-500">Expiring in 0–2 days</div><div class="text-2xl font-black text-rose-700 mt-1">{{ $stats['expiring'] }}</div></a>
    <a href="{{ route('admin.jobs.index',['section'=>'jobs','deadline'=>'expired']) }}" class="bg-slate-100 border border-slate-200 rounded-2xl p-4"><div class="text-[10px] font-black uppercase text-slate-500">Expired</div><div class="text-2xl font-black text-slate-800 mt-1">{{ $stats['expired'] }}</div></a>
    <div class="bg-white border rounded-2xl p-4"><div class="text-[10px] font-black uppercase text-slate-400">Total Views</div><div class="text-2xl font-black mt-1">{{ number_format($stats['views']) }}</div></div>
    <div class="bg-white border rounded-2xl p-4"><div class="text-[10px] font-black uppercase text-slate-400">Apply Clicks</div><div class="text-2xl font-black mt-1">{{ number_format($stats['apply_clicks']) }}</div></div>
    <div class="bg-white border rounded-2xl p-4"><div class="text-[10px] font-black uppercase text-slate-400">Notifications</div><div class="text-2xl font-black mt-1">{{ number_format($stats['notifications']) }}</div></div>
  </div>
  <div class="grid lg:grid-cols-2 gap-5">
    <div class="bg-white border rounded-2xl overflow-hidden"><div class="px-5 py-4 border-b"><h3 class="font-black text-sm">Category Distribution</h3></div><div class="p-5 space-y-3">@forelse($categoryStats as $row)<div><div class="flex justify-between text-xs mb-1"><span class="font-bold">{{ $row->job_category ?: 'Uncategorized' }}</span><span class="text-slate-500">{{ $row->total }}</span></div><div class="h-2 bg-slate-100 rounded-full overflow-hidden"><div class="h-full bg-brand-500 rounded-full" style="width:{{ min(100,($row->total/max(1,$stats['total']))*100) }}%"></div></div></div>@empty<p class="text-xs text-slate-400">No jobs yet.</p>@endforelse</div></div>
    <div class="bg-white border rounded-2xl overflow-hidden"><div class="px-5 py-4 border-b"><h3 class="font-black text-sm">Top Departments</h3></div><div class="p-5 grid grid-cols-2 gap-2">@forelse($departmentStats as $row)<div class="p-3 rounded-xl bg-slate-50"><div class="text-xs font-bold text-slate-700">{{ $row->department }}</div><div class="text-lg font-black text-brand-700">{{ $row->total }}</div></div>@empty<p class="text-xs text-slate-400">No departments yet.</p>@endforelse</div></div>
  </div>
  <div class="grid lg:grid-cols-2 gap-5">
    <div class="bg-white border rounded-2xl overflow-hidden"><div class="px-5 py-4 border-b flex justify-between"><h3 class="font-black text-sm">Upcoming Deadlines</h3><a href="{{ route('admin.jobs.index',['section'=>'jobs','deadline'=>'closing']) }}" class="text-xs font-bold text-brand-600">View all</a></div><div class="divide-y">@forelse($upcoming as $job)<div class="px-5 py-3 flex justify-between gap-3"><div class="min-w-0"><div class="text-xs font-bold truncate">{{ $job->title }}</div><div class="text-[10px] text-slate-500">{{ $job->job_category }} → {{ $job->department }}</div></div><span class="text-[10px] font-black text-rose-600 whitespace-nowrap">{{ $job->last_date }}</span></div>@empty<div class="p-6 text-xs text-slate-400">No upcoming deadlines found.</div>@endforelse</div></div>
    <div class="bg-white border rounded-2xl overflow-hidden"><div class="px-5 py-4 border-b"><h3 class="font-black text-sm">Most Viewed Jobs</h3></div><div class="divide-y">@forelse($topJobs as $job)<div class="px-5 py-3 flex justify-between gap-3"><div class="min-w-0"><div class="text-xs font-bold truncate">{{ $job->title }}</div><div class="text-[10px] text-slate-500">{{ $job->job_category }} → {{ $job->department }}</div></div><span class="text-[10px] font-black text-slate-600 whitespace-nowrap"><i class="fa-regular fa-eye mr-1"></i>{{ number_format($job->views_count) }}</span></div>@empty<div class="p-6 text-xs text-slate-400">Analytics will appear after users visit jobs.</div>@endforelse</div></div>
  </div>
</div>
@endsection
