@extends('layouts.admin')
@section('title','Modify Job')
@section('content')
<div class="max-w-5xl mx-auto space-y-6"><div class="flex items-center justify-between"><div><h2 class="text-xl font-black text-slate-900">Modify Job</h2><p class="text-xs text-slate-500">ID: {{ $job->custom_id ?: $job->id }} · Status: {{ ucfirst($job->workflow_status ?: 'published') }}</p></div><a href="{{ route('admin.jobs.index',['section'=>'jobs']) }}" class="px-3 py-2 border rounded-xl text-xs font-bold">← Back</a></div>
<form method="POST" action="{{ route('admin.jobs.update',$job) }}" class="bg-white rounded-3xl border shadow-sm p-6 sm:p-8 space-y-6">@csrf @method('PUT')
<div class="grid md:grid-cols-4 gap-4 bg-slate-50 p-4 rounded-2xl"><div><label class="label">Main Category *</label><select name="job_category" required class="input">@foreach($jobCategories as $c)<option value="{{ $c }}" @selected(old('job_category',$job->job_category)===$c)>{{ $c }}</option>@endforeach</select></div><div><label class="label">Department *</label><select name="department" required class="input">@foreach($departments as $d)<option value="{{ $d }}" @selected(old('department',$job->department)===$d)>{{ $d }}</option>@endforeach</select></div><div><label class="label">Post Type</label><select name="post_type" class="input">@foreach($postTypes as $v=>$label)<option value="{{ $v }}" @selected(old('post_type',$job->post_type)===$v)>{{ $label }}</option>@endforeach</select></div><div><label class="label">Workflow</label><select name="workflow_status" id="workflow_status" class="input">@foreach(['published'=>'Published','draft'=>'Draft','scheduled'=>'Scheduled','archived'=>'Archived'] as $v=>$label)<option value="{{ $v }}" @selected(old('workflow_status',$job->workflow_status?:'published')===$v)>{{ $label }}</option>@endforeach</select></div><input type="hidden" name="section" value="jobs"></div>
<div id="scheduleBox" class="{{ old('workflow_status',$job->workflow_status)==='scheduled'?'':'hidden' }} bg-blue-50 border border-blue-100 rounded-2xl p-4"><label class="label">Publish Date & Time *</label><input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at',$job->scheduled_at?->format('Y-m-d\TH:i')) }}" class="input"></div>
<div class="grid md:grid-cols-3 gap-5"><div class="md:col-span-2"><label class="label">Job Name *</label><input name="title" value="{{ old('title',$job->title_en ?: $job->title) }}" required class="input"></div><div><label class="label">Released By / Organization</label><input name="source" value="{{ old('source',$job->source) }}" class="input"></div></div>
<div class="grid md:grid-cols-4 gap-4"><div><label class="label">Total Posts</label><input name="vacancies" value="{{ old('vacancies',$job->vacancies) }}" class="input"></div><div><label class="label">Apply From</label><input name="application_start" value="{{ old('application_start',$job->application_start) }}" class="input"></div><div><label class="label">Last Date</label><input name="last_date" value="{{ old('last_date',$job->last_date) }}" class="input"></div><div><label class="label">Exam Date</label><input name="exam_date" value="{{ old('exam_date',$job->exam_date) }}" class="input"></div></div>
<div class="grid md:grid-cols-4 gap-4"><div><label class="label">Admit Card Date</label><input name="admit_card_date" value="{{ old('admit_card_date',$job->admit_card_date) }}" class="input"></div><div><label class="label">Result Date</label><input name="result_date" value="{{ old('result_date',$job->result_date) }}" class="input"></div><div><label class="label">Age Limit</label><input name="age_limit" value="{{ old('age_limit',$job->age_limit) }}" class="input"></div><div><label class="label">Salary</label><input name="salary" value="{{ old('salary',$job->salary) }}" class="input"></div></div>
<div><label class="label">Eligibility</label><input name="eligibility" value="{{ old('eligibility',$job->eligibility_en ?: $job->eligibility) }}" class="input"></div><div><label class="label">Selection Process</label><input name="selection_process" value="{{ old('selection_process',$job->selection_process_en ?: $job->selection_process) }}" class="input"></div><div><label class="label">Short Summary *</label><textarea name="summary" rows="3" required class="input">{{ old('summary',$job->summary_en ?: $job->summary) }}</textarea></div><div><label class="label">Detailed Information</label><textarea name="detailed_content" rows="8" class="input">{{ old('detailed_content',$job->detailed_content_en ?: $job->detailed_content) }}</textarea></div>
<div class="grid md:grid-cols-2 gap-5"><div><label class="label">Official Notification URL</label><input type="url" name="official_notification_url" value="{{ old('official_notification_url',$job->official_notification_url) }}" class="input"></div><div><label class="label">Apply Online URL</label><input type="url" name="apply_url" value="{{ old('apply_url',$job->apply_url) }}" class="input"></div><div><label class="label">Source URL</label><input type="url" name="source_url" value="{{ old('source_url',$job->source_url) }}" class="input"></div><div><label class="label">Source Image URL</label><input type="url" name="image_url" value="{{ old('image_url',$job->image_url) }}" class="input"></div></div>
<div class="flex flex-wrap gap-6 border-t pt-4"><label class="check"><input type="checkbox" name="is_breaking" value="1" @checked(old('is_breaking',$job->is_breaking))> HOT / Breaking</label><label class="check"><input type="checkbox" name="is_new" value="1" @checked(old('is_new',$job->is_new))> New</label></div><div class="flex justify-end"><button class="px-6 py-3 rounded-xl bg-brand-600 text-white font-black">Save Changes</button></div></form></div>
<style>.label{display:block;font-size:11px;font-weight:800;color:#475569;margin-bottom:6px;text-transform:uppercase;letter-spacing:.04em}.input{width:100%;border:1px solid #dbe2ea;border-radius:12px;padding:11px 13px;background:#fff;font-size:14px;outline:none}.check{font-size:13px;font-weight:700;color:#475569;display:flex;gap:8px;align-items:center}.hidden{display:none}</style><script>const w=document.getElementById('workflow_status'),b=document.getElementById('scheduleBox');w.addEventListener('change',()=>b.classList.toggle('hidden',w.value!=='scheduled'));</script>
@endsection
