<!DOCTYPE html>
<html lang="hi" class="h-full bg-slate-50">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@yield('title','CGJobs Admin Portal') | छत्तीसगढ़ रोजगार व परीक्षा पोर्टल</title>
<script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<style>body{font-family:Inter,'Noto Sans Devanagari',sans-serif}#admin-sidebar{transition:transform .25s ease,width .25s ease}#admin-backdrop{transition:opacity .2s ease}@media (min-width:768px){#admin-sidebar.admin-collapsed{width:0;overflow:hidden;transform:translateX(-100%)}}@media (max-width:767px){#admin-sidebar{position:fixed;z-index:50;left:0;top:0;bottom:0;width:18rem;max-width:88vw;transform:translateX(-105%);padding:1rem;overflow-y:auto}#admin-sidebar.admin-open{transform:translateX(0)}#admin-backdrop.admin-open{display:block;opacity:1}}</style>
</head>
<body class="h-full flex flex-col bg-slate-100 text-slate-800">
<header class="bg-blue-800 text-white shadow-md sticky top-0 z-40"><div class="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between gap-3"><div class="flex items-center gap-3 min-w-0"><button id="admin-menu-toggle" type="button" aria-label="साइडबार खोलें" aria-expanded="false" aria-controls="admin-sidebar" class="w-10 h-10 shrink-0 inline-flex items-center justify-center rounded-xl text-white hover:bg-white/15 focus:outline-none focus:ring-2 focus:ring-white/80 transition"><i id="admin-menu-icon" class="fa-solid fa-bars text-lg" aria-hidden="true"></i></button><div class="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center shrink-0"><i class="fa-solid fa-briefcase text-orange-400 text-xl" aria-hidden="true"></i></div><div class="min-w-0"><h1 class="text-lg font-bold truncate">CGJobs Admin</h1><p class="text-xs text-blue-200 truncate">छत्तीसगढ़ रोजगार व सूचना प्रबंधन पोर्टल</p></div></div><form action="{{route('admin.logout')}}" method="POST">@csrf<button class="px-3 py-1.5 rounded-lg text-xs bg-rose-500 hover:bg-rose-600 focus:outline-none focus:ring-2 focus:ring-white/80 transition">Logout</button></form></div></header>
<div id="admin-backdrop" class="hidden fixed inset-0 z-40 bg-slate-950/50 opacity-0 md:hidden" aria-hidden="true"></div>
<div class="flex-1 flex max-w-7xl w-full mx-auto px-4 py-6 gap-6 relative"><aside id="admin-sidebar" class="w-64 shrink-0"><nav class="bg-white rounded-2xl shadow-sm border border-slate-200 p-3 space-y-1 min-h-full">
<a href="{{route('admin.dashboard')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-blue-500"><i class="fa-solid fa-gauge-high w-5 text-blue-600"></i>डैशबोर्ड</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">Jobs</div>
@php $links=[['admin.jobs.dashboard','Dashboard','fa-chart-pie'],['admin.jobs.index','All Jobs','fa-briefcase'],['admin.jobs.create','Create New Job','fa-circle-plus'],['admin.jobs.republished','Republished','fa-rotate'],['admin.jobs.templates','Job Templates','fa-file-lines'],['admin.jobs.categories','Categories & Departments','fa-sitemap'],['admin.jobs.notifications','Notification Center','fa-bell'],['admin.jobs.import-sync','Import / Sync','fa-cloud-arrow-down'],['admin.jobs.quality','Job Quality Checker','fa-circle-check'],['admin.jobs.duplicates','Duplicate Detection','fa-copy'],['admin.jobs.analytics','Advanced Analytics','fa-chart-line']]; @endphp
@foreach($links as $l)<a href="{{route($l[0],$l[0]==='admin.jobs.index'?['section'=>'jobs']:[])}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm {{request()->routeIs($l[0])?'font-semibold text-blue-700 bg-blue-50':'text-slate-600 hover:bg-slate-50'}} focus:outline-none focus:ring-2 focus:ring-blue-500"><i class="fa-solid {{$l[2]}} w-5 text-blue-600"></i>{{$l[1]}}</a>@endforeach
<a href="{{route('admin.jobs.index',['section'=>'jobs','workflow_status'=>'draft'])}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-file-pen w-5 text-amber-600"></i>Drafts</a><a href="{{route('admin.jobs.index',['section'=>'jobs','workflow_status'=>'scheduled'])}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-calendar-days w-5 text-purple-600"></i>Scheduled Jobs</a><a href="{{route('admin.jobs.index',['section'=>'jobs','deadline'=>'closing'])}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-fire w-5 text-rose-500"></i>Expiring Soon</a><a href="{{route('admin.jobs.index',['section'=>'jobs','deadline'=>'expired'])}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-clock-rotate-left w-5 text-slate-500"></i>Expired Jobs</a><a href="{{route('admin.jobs.index',['section'=>'jobs'])}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-layer-group w-5 text-indigo-600"></i>Bulk Manager</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">Content</div><a href="{{route('admin.ai-engine.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm {{request()->routeIs('admin.ai-engine.*')?'font-semibold text-purple-700 bg-purple-50':'text-slate-600 hover:bg-slate-50'}}"><i class="fa-solid fa-robot w-5 text-purple-600"></i>AI Content Engine</a><a href="{{route('admin.jobs.index',['section'=>'news'])}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-newspaper w-5 text-cyan-600"></i>News / Current Affairs</a><a href="{{route('admin.static-gk.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-book-open w-5 text-indigo-600"></i>Static GK</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">Automation</div><a href="{{route('admin.job-sources.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-plug w-5 text-cyan-600"></i>Jobs API / Sources</a><a href="{{route('admin.sync.index')}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-cloud-arrow-down w-5 text-cyan-600"></i>News Sync</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">System</div><a href="{{route('admin.alerts.index')}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-bell w-5 text-amber-500"></i>Alerts</a><a href="{{route('admin.categories.index')}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-tags w-5 text-teal-600"></i>Categories</a><a href="{{route('admin.settings.index')}}" class="flex gap-3 px-3 py-2 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-sliders w-5 text-amber-500"></i>Settings</a>
</nav></aside><main class="flex-1 min-w-0">@if(session('success'))<div class="mb-5 bg-emerald-50 border border-emerald-200 text-emerald-800 px-4 py-3.5 rounded-2xl">{{session('success')}}</div>@endif @if(session('info'))<div class="mb-5 bg-blue-50 border border-blue-200 text-blue-800 px-4 py-3.5 rounded-2xl">{{session('info')}}</div>@endif @if($errors->any())<div class="mb-5 bg-rose-50 border border-rose-200 text-rose-800 px-4 py-3.5 rounded-2xl"><ul class="list-disc list-inside text-xs">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif @yield('content')</main></div>
<footer class="bg-white border-t mt-auto py-4 text-center text-xs text-slate-500">CGJobs Portal Backend &copy; {{date('Y')}}</footer>
<script>(function(){const sidebar=document.getElementById('admin-sidebar'),backdrop=document.getElementById('admin-backdrop'),toggle=document.getElementById('admin-menu-toggle'),icon=document.getElementById('admin-menu-icon');if(!sidebar||!toggle)return;const mobile=()=>window.matchMedia('(max-width: 767px)').matches;function setState(open){if(mobile()){sidebar.classList.toggle('admin-open',open);backdrop.classList.toggle('hidden',!open);backdrop.classList.toggle('admin-open',open);document.body.classList.toggle('overflow-hidden',open)}else{sidebar.classList.toggle('admin-collapsed',!open);localStorage.setItem('cgjobs-admin-sidebar-collapsed',open?'0':'1')}toggle.setAttribute('aria-expanded',open?'true':'false');toggle.setAttribute('aria-label',open?'साइडबार बंद करें':'साइडबार खोलें');icon.className='fa-solid '+(open?'fa-xmark':'fa-bars')+' text-lg'}const collapsed=localStorage.getItem('cgjobs-admin-sidebar-collapsed')==='1';setState(!collapsed);toggle.addEventListener('click',()=>{const open=mobile()?sidebar.classList.contains('admin-open'):!sidebar.classList.contains('admin-collapsed');setState(!open)});backdrop.addEventListener('click',()=>setState(false));window.addEventListener('resize',()=>{if(!mobile()){backdrop.classList.add('hidden');document.body.classList.remove('overflow-hidden');setState(localStorage.getItem('cgjobs-admin-sidebar-collapsed')!=='1')}});sidebar.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(mobile())setState(false)}))})();</script>
</body></html>
