<!DOCTYPE html>
<html lang="hi" class="h-full bg-slate-50">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>@yield('title','CGJobs Admin Portal') | छत्तीसगढ़ रोजगार व परीक्षा पोर्टल</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Noto+Sans+Devanagari:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><style>body{font-family:'Inter','Noto Sans Devanagari',sans-serif}</style></head>
<body class="h-full flex flex-col bg-slate-100 text-slate-800">
<header class="bg-blue-800 text-white shadow-md"><div class="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between"><div class="flex items-center gap-3"><div class="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><i class="fa-solid fa-briefcase text-orange-400 text-xl"></i></div><div><h1 class="text-lg font-bold">CGJobs Admin</h1><p class="text-xs text-blue-200">छत्तीसगढ़ रोजगार व सूचना प्रबंधन पोर्टल</p></div></div><div class="flex items-center gap-4"><a href="{{url('/api/health')}}" target="_blank" class="hidden sm:block text-xs bg-emerald-500/20 text-emerald-200 px-3 py-1 rounded-full">● API Active</a><form action="{{route('admin.logout')}}" method="POST">@csrf<button class="px-3 py-1.5 rounded-lg text-xs bg-rose-500">Logout</button></form></div></div></header>
<div class="flex-1 flex max-w-7xl w-full mx-auto px-4 py-6 gap-6"><aside class="w-64 shrink-0 hidden md:block"><nav class="bg-white rounded-2xl shadow-sm border p-3 space-y-1">
<a href="{{route('admin.dashboard')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-gauge-high w-5 text-blue-600"></i>डैशबोर्ड</a><div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">Jobs</div>
<a href="{{route('admin.jobs.index',['section'=>'jobs'])}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm {{request('section','jobs')==='jobs'?'font-semibold text-blue-700 bg-blue-50':'text-slate-600 hover:bg-slate-50'}}"><i class="fa-solid fa-briefcase w-5 text-blue-600"></i>All Jobs</a><a href="{{route('admin.jobs.create',['section'=>'jobs'])}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-circle-plus w-5 text-emerald-600"></i>Create New Job</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">Content</div><a href="{{route('admin.jobs.index',['section'=>'news'])}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-newspaper w-5 text-cyan-600"></i>News / Current Affairs</a><a href="{{route('admin.static-gk.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-book-open w-5 text-indigo-600"></i>Static GK</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">Automation</div><a href="{{route('admin.job-sources.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-plug w-5 text-cyan-600"></i>Jobs API / Sources</a><a href="{{route('admin.sync.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-cloud-arrow-down w-5 text-cyan-600"></i>News Sync</a>
<div class="pt-3 pb-1 px-3 text-[11px] font-bold text-slate-400 uppercase">System</div><a href="{{route('admin.alerts.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-bell w-5 text-amber-500"></i>Alerts</a><a href="{{route('admin.sections.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-layer-group w-5 text-purple-600"></i>Sections</a><a href="{{route('admin.categories.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-tags w-5 text-teal-600"></i>Categories</a><a href="{{route('admin.settings.index')}}" class="flex gap-3 px-3 py-2.5 rounded-xl text-sm text-slate-600 hover:bg-slate-50"><i class="fa-solid fa-sliders w-5 text-amber-500"></i>Settings</a>
<form action="{{route('admin.cache.clear')}}" method="POST" class="pt-2">@csrf<button type="submit" class="w-full flex gap-3 px-3 py-2.5 rounded-xl text-sm text-amber-700 hover:bg-amber-50 text-left"><i class="fa-solid fa-broom w-5"></i>Clear Cache</button></form></nav></aside><main class="flex-1 min-w-0">
@if(session('success'))<div class="mb-5 bg-emerald-50 border border-emerald-200 text-emerald-800 px-4 py-3.5 rounded-2xl">{{session('success')}}</div>@endif @if(session('info'))<div class="mb-5 bg-blue-50 border border-blue-200 text-blue-800 px-4 py-3.5 rounded-2xl">{{session('info')}}</div>@endif @if($errors->any())<div class="mb-5 bg-rose-50 border border-rose-200 text-rose-800 px-4 py-3.5 rounded-2xl"><ul class="list-disc list-inside text-xs">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
@yield('content')</main></div><footer class="bg-white border-t mt-auto py-4 text-center text-xs text-slate-500">CGJobs Portal Backend &copy; {{date('Y')}}</footer></body></html>
