<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Alert;
use App\Models\Category;
use App\Models\Job;
use App\Services\FirebaseNotificationService;
use App\Services\TranslationService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class JobManagementController extends Controller
{
    private const CATEGORIES=['CGSSB','CGPSC','Central Govt','Contractual'];
    private const DEPARTMENTS=['Education','Police','Revenue','PHE','PWD','Health','Women & Child Development','Forest','Agriculture','Panchayat','Transport','Other Departments'];
    private const TYPES=['job'=>'Job Notification','admit_card'=>'Admit Card','result'=>'Result','syllabus'=>'Syllabus','answer_key'=>'Answer Key'];

    private function jobs(){return Job::query()->where(fn($q)=>$q->where('section','jobs')->orWhereNull('section'));}
    private function publicJobs($q){return $q->where(fn($x)=>$x->whereNull('workflow_status')->orWhere('workflow_status','published'));}

    public function dashboard(){
        $base=$this->jobs();$published=$this->publicJobs(clone $base);
        $stats=['total'=>(clone $base)->count(),'published'=>(clone $published)->count(),'drafts'=>(clone $base)->where('workflow_status','draft')->count(),'scheduled'=>(clone $base)->where('workflow_status','scheduled')->count(),'archived'=>(clone $base)->where('workflow_status','archived')->count(),'expiring'=>$this->deadlineCount(false),'expired'=>$this->deadlineCount(true),'views'=>(int)(clone $base)->sum('views_count'),'apply_clicks'=>(int)(clone $base)->sum('apply_clicks'),'notifications'=>(int)(clone $base)->sum('notification_count')];
        $categoryStats=(clone $base)->select('job_category',DB::raw('COUNT(*) total'))->groupBy('job_category')->orderByDesc('total')->get();
        $departmentStats=(clone $base)->select('department',DB::raw('COUNT(*) total'))->whereNotNull('department')->where('department','!=','')->groupBy('department')->orderByDesc('total')->take(10)->get();
        $upcoming=(clone $published)->whereNotNull('last_date')->get()->filter(fn($j)=>($d=$this->parseDate($j->last_date))&&$d->gte(now()->startOfDay()))->sortBy(fn($j)=>$this->parseDate($j->last_date)?->timestamp)->take(8);
        $topJobs=(clone $base)->orderByDesc('views_count')->orderByDesc('id')->take(8)->get();
        return view('admin.jobs.dashboard',compact('stats','categoryStats','departmentStats','upcoming','topJobs'));
    }

    public function index(Request $r){
        $q=$this->jobs();if($r->filled('search')){$s='%'.$r->search.'%';$q->where(fn($x)=>$x->where('title','like',$s)->orWhere('title_en','like',$s)->orWhere('summary','like',$s)->orWhere('summary_en','like',$s)->orWhere('vacancies','like',$s)->orWhere('source','like',$s));}
        foreach(['job_category','department','source','workflow_status','post_type'] as $f)if($r->filled($f))$q->where($f,$f==='source'?'like':'=',$f==='source'?'%'.$r->$f.'%':$r->$f);
        if($r->filled('published_from'))$q->whereDate('published_at','>=',$r->published_from);if($r->filled('published_to'))$q->whereDate('published_at','<=',$r->published_to);
        if($r->deadline==='expired')$q->whereRaw($this->dateSql().' < CURDATE()');elseif($r->deadline==='closing')$q->whereRaw($this->dateSql().' BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 2 DAY)');elseif($r->deadline==='open')$q->where(fn($x)=>$x->whereNull('last_date')->orWhere('last_date','')->orWhereRaw($this->dateSql().' > DATE_ADD(CURDATE(),INTERVAL 2 DAY)'));
        $sort=$r->get('sort','latest');$sort==='oldest'?$q->orderBy('id'):($sort==='title'?$q->orderBy('title'):($sort==='views'?$q->orderByDesc('views_count')->orderByDesc('id'):$q->orderByDesc('id')));$jobs=$q->paginate(15)->withQueryString();$sources=$this->jobs()->whereNotNull('source')->where('source','!=','')->distinct()->orderBy('source')->pluck('source');
        return view('admin.jobs.index',compact('jobs','sources'))->with('jobCategories',self::CATEGORIES)->with('departments',self::DEPARTMENTS)->with('postTypes',self::TYPES);
    }

    public function create(Request $r){return view('admin.jobs.create',['categories'=>Category::orderBy('name')->get(),'defaultSection'=>'jobs','jobCategories'=>self::CATEGORIES,'departments'=>self::DEPARTMENTS,'postTypes'=>self::TYPES,'template'=>$r->query('template')]);}

    public function store(Request $r, FirebaseNotificationService $fcm, TranslationService $translator){$data=$this->validatePost($r);$status=$r->input('workflow_status','published');if(!in_array($status,Job::WORKFLOW_STATUSES,true))$status='published';if($status==='scheduled'&&(!$r->filled('scheduled_at')||Carbon::parse($r->scheduled_at)->isPast()))return back()->withErrors(['scheduled_at'=>'Choose a future publish date and time.'])->withInput();$data=$this->prepare($data,$r);$data['workflow_status']=$status;$data['scheduled_at']=$status==='scheduled'?Carbon::parse($r->scheduled_at):null;$data['published_at']=$status==='published'?date('Y-m-d'):null;$job=Job::create($data);$this->translate($job,$translator);if($status==='published'&&$r->has('broadcast_push'))$this->notify($job,$fcm,'NEW_JOB');return redirect()->route('admin.jobs.index',['section'=>'jobs'])->with('success',$status==='draft'?'Job saved as draft.':($status==='scheduled'?'Job scheduled.':'Job published.'));}

    public function edit(Job $job){return view('admin.jobs.edit',['job'=>$job,'categories'=>Category::orderBy('name')->get(),'jobCategories'=>self::CATEGORIES,'departments'=>self::DEPARTMENTS,'postTypes'=>self::TYPES]);}
    public function update(Request $r,Job $job,TranslationService $translator){$data=$this->validatePost($r);$status=$r->input('workflow_status',$job->workflow_status?:'published');if(!in_array($status,Job::WORKFLOW_STATUSES,true))$status='published';$scheduled=$status==='scheduled'?Carbon::parse($r->scheduled_at?:$job->scheduled_at):null;if($status==='scheduled'&&(!$scheduled||$scheduled->isPast()))return back()->withErrors(['scheduled_at'=>'Choose a future publish date and time.'])->withInput();$lastChanged=array_key_exists('last_date',$data)&&$data['last_date']!==$job->last_date;$data=$this->prepare($data,$r);$data['workflow_status']=$status;$data['scheduled_at']=$scheduled;if($status==='published'&&$job->workflow_status!=='published')$data['published_at']=date('Y-m-d');if($lastChanged)$data['closing_reminder_sent_at']=null;$job->update($data);$this->translate($job->fresh(),$translator);return redirect()->route('admin.jobs.index',['section'=>'jobs'])->with('success',$status==='draft'?'Draft saved.':($status==='scheduled'?'Job scheduled.':'Job updated.'));}

    public function publish(Job $job,FirebaseNotificationService $fcm){$this->guard($job);$job->update(['workflow_status'=>'published','scheduled_at'=>null,'published_at'=>date('Y-m-d'),'relative_time'=>'हाल ही में','relative_time_en'=>'Recently','is_new'=>true]);$ok=$this->notify($job,$fcm,'JOB_PUBLISH');return back()->with($ok?'success':'info',$ok?'Job published and notification sent.':'Job published, notification could not be confirmed.');}
    public function republish(Job $job,FirebaseNotificationService $fcm){$this->guard($job);$job->update(['workflow_status'=>'published','scheduled_at'=>null,'published_at'=>date('Y-m-d'),'relative_time'=>'हाल ही में','relative_time_en'=>'Recently','is_new'=>true]);$ok=$this->notify($job,$fcm,'RECRUITMENT_REPUBLISH');return back()->with($ok?'success':'info',$ok?'Job republished and notification sent.':'Job republished, notification could not be confirmed.');}

    public function bulkAction(Request $r,FirebaseNotificationService $fcm){$ids=array_filter((array)$r->input('job_ids',[]),'is_numeric');if(!$ids)return back()->with('info','Select at least one job.');$jobs=$this->jobs()->whereIn('id',$ids)->get();$action=$r->input('bulk_action');$n=0;foreach($jobs as $job){switch($action){case'delete':$job->delete();break;case'publish':$job->update(['workflow_status'=>'published','published_at'=>date('Y-m-d'),'scheduled_at'=>null,'is_new'=>true]);break;case'draft':$job->update(['workflow_status'=>'draft']);break;case'archive':$job->update(['workflow_status'=>'archived']);break;case'hot':$job->update(['is_breaking'=>true]);break;case'new':$job->update(['is_new'=>true]);break;case'notify':$this->notify($job,$fcm,'BULK_JOB');break;default:continue 2;}$n++;}return back()->with('success',"Bulk action completed for {$n} job(s).");}

    public function destroy(Job $job){$this->guard($job);$job->delete();return back()->with('success','Job deleted.');}
    public function templates(){return view('admin.jobs.templates',['templates'=>[['key'=>'cgssb','name'=>'CGSSB Recruitment','category'=>'CGSSB','department'=>'Education'],['key'=>'cgpsc','name'=>'CGPSC Recruitment','category'=>'CGPSC','department'=>'Other Departments'],['key'=>'central','name'=>'Central Government Recruitment','category'=>'Central Govt','department'=>'Other Departments'],['key'=>'contractual','name'=>'Contractual Recruitment','category'=>'Contractual','department'=>'Other Departments'],['key'=>'teacher','name'=>'Teacher Recruitment','category'=>'CGSSB','department'=>'Education'],['key'=>'police','name'=>'Police Recruitment','category'=>'CGSSB','department'=>'Police']]]);}

    private function notify(Job $job,FirebaseNotificationService $fcm,string $type):bool{$id=(string)($job->custom_id?:$job->id);$title=($type==='RECRUITMENT_REPUBLISH'?'फिर से प्रकाशित: ':'नई भर्ती: ').trim((string)($job->title?:$job->title_en));$message=trim((string)($job->summary?:$job->summary_en))?:'नई भर्ती की जानकारी उपलब्ध है।';$a=Alert::create(['category'=>$job->job_category?:'CGSSB','title'=>$title,'short_description'=>$message,'time'=>'हाल ही में','type'=>$type,'article_id'=>$id,'action_url'=>route('job.show',$id),'is_broadcasted'=>false]);$res=$fcm->broadcast(title:$a->title,message:$a->short_description,category:$a->category,actionUrl:$a->action_url,articleId:$id);$ok=($res['success']??false)===true;if($ok){$a->update(['is_broadcasted'=>true]);$job->update(['notification_count'=>((int)$job->notification_count)+1,'last_notification_at'=>now()]);}return $ok;}
    private function guard(Job $job):void{abort_unless($job->section==='jobs'||is_null($job->section),404);}
    private function prepare(array $d,Request $r):array{$d['section']='jobs';$d['post_type']=$r->input('post_type','job');$d['is_breaking']=$r->has('is_breaking');$d['is_new']=$r->has('is_new');$d['relative_time']='हाल ही में';$d['relative_time_en']='Recently';$d['title_en']=$d['title'];$d['summary_en']=$d['summary'];$d['detailed_content_en']=$d['detailed_content']??null;$d['eligibility_en']=$d['eligibility']??null;$d['selection_process_en']=$d['selection_process']??null;$d['translation_status']='pending';$d['category']=$d['department'];$d['category_en']=$d['department'];return $d;}
    private function validatePost(Request $r):array{return $r->validate(['title'=>'required|string|max:255','summary'=>'required|string','detailed_content'=>'nullable|string','job_category'=>'required|in:CGSSB,CGPSC,Central Govt,Contractual','department'=>'required|string|max:120','post_type'=>'nullable|string','vacancies'=>'nullable|string','salary'=>'nullable|string','eligibility'=>'nullable|string','age_limit'=>'nullable|string','selection_process'=>'nullable|string','source'=>'nullable|string','source_url'=>'nullable|url','official_notification_url'=>'nullable|url','apply_url'=>'nullable|url','image_url'=>'nullable|url','application_start'=>'nullable|string','last_date'=>'nullable|string','exam_date'=>'nullable|string','admit_card_date'=>'nullable|string','result_date'=>'nullable|string','workflow_status'=>'nullable|in:draft,scheduled,published,archived','scheduled_at'=>'nullable|date']);}
    private function translate(Job $job,TranslationService $t):void{try{$x=$t->translateMany(['title'=>$job->title_en,'summary'=>$job->summary_en,'detailed'=>$job->detailed_content_en,'category'=>$job->category_en,'eligibility'=>$job->eligibility_en,'selection'=>$job->selection_process_en]);$ready=!empty($x['title']);$job->update(['title'=>$x['title']?:$job->title_en,'summary'=>$x['summary']?:$job->summary_en,'detailed_content'=>$x['detailed']?:$job->detailed_content_en,'category'=>$x['category']?:$job->category_en,'eligibility'=>$x['eligibility']?:$job->eligibility_en,'selection_process'=>$x['selection']?:$job->selection_process_en,'translation_status'=>$ready?'ready':'pending','translation_error'=>$ready?null:'Automatic Hindi translation temporarily unavailable.','translated_at'=>$ready?now():null]);}catch(\Throwable){$job->update(['translation_status'=>'failed','translation_error'=>'Automatic Hindi translation temporarily unavailable.']);}}
    private function dateSql():string{return "COALESCE(STR_TO_DATE(last_date,'%d/%m/%Y'),STR_TO_DATE(last_date,'%d-%m-%Y'),STR_TO_DATE(last_date,'%Y-%m-%d'),STR_TO_DATE(last_date,'%d %b %Y'),STR_TO_DATE(last_date,'%d %M %Y'))";}
    private function deadlineCount(bool $expired):int{$q=$this->publicJobs($this->jobs())->whereNotNull('last_date')->where('last_date','!=','');$sql=$this->dateSql();return $expired?$q->whereRaw("{$sql} < CURDATE()")->count():$q->whereRaw("{$sql} BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 2 DAY)")->count();}
    private function parseDate(?string $v):?Carbon{$v=trim((string)$v);if($v===''||in_array(mb_strtolower($v),['soon','शीघ्र','open','ongoing'],true))return null;try{return Carbon::parse($v)->startOfDay();}catch(\Throwable){return null;}}
}
